#!/bin/bash
set -euo pipefail

# Build Gemmini in CPU fallback mode on Apple Silicon; outputs live in build-arm64/bin by default.
BUILD_DIR=${BUILD_DIR:-build-arm64}
LLAMA_CURL_DEFAULT=${LLAMA_CURL_DEFAULT:-OFF} # disable libcurl requirement on local macOS unless explicitly enabled
CMAKE_BUILD_TYPE_DEFAULT=${CMAKE_BUILD_TYPE_DEFAULT:-Release} # Debug | Release
GGML_NATIVE_DEFAULT=${GGML_NATIVE_DEFAULT:-ON} # ON | OFF
LOG_DEBUG_DEFAULT=${LOG_DEBUG:-1} # 0 | 1
LOG_CYCLE_DEFAULT=${LOG_CYCLE:-1} # 0 | 1
GGML_CPU_CYCLE_LOG_DEFAULT=${GGML_CPU_CYCLE_LOG:-${LOG_CYCLE_DEFAULT}}
CYCLE_DETAIL_DEFAULT=${CYCLE_DETAIL:-1}
LOG_DUMP_DEFAULT=${LOG_DUMP:-0} # 0 | 1
LOG_DUMP_SCALE_DEFAULT=${LOG_DUMP_SCALE:-0} # 0 | 1
GGML_GEMMINI_PRINT_TILE_DEFAULT=${GGML_GEMMINI_PRINT_TILE:-0} # 0 | 1
GGML_GEMMINI_OPTION_DEFAULT=${GGML_GEMMINI_OPTION:-CPU} # CPU | OS | WS
GGML_GEMMINI_FULL_C_DEFAULT=${GGML_GEMMINI_FULL_C:-1} # 0 | 1
GGML_GEMMINI_LOW_D_DEFAULT=${GGML_GEMMINI_LOW_D:-0} # 0 | 1
GGML_GEMMINI_TRANSPOSE_B_DEFAULT=${GGML_GEMMINI_TRANSPOSE_B:-1} # 0 | 1
GGML_GEMMINI_WS_LOOP_DEBUG_DEFAULT=${GGML_GEMMINI_WS_LOOP_DEBUG:-0}
APPLE_SILICON_ARCH_DEFAULT=${APPLE_SILICON_ARCH:-arm64}
BUILD_JOBS_DEFAULT=${BUILD_JOBS:-$(sysctl -n hw.logicalcpu)}
GGML_OPENMP_DEFAULT=${GGML_OPENMP:-ON}
GGML_GEMMINI_ENABLE_OPENMP_DEFAULT=${GGML_GEMMINI_ENABLE_OPENMP:-ON}
# ExSIA Local/Folding pipeline uses a fixed five-thread OpenMP team.
LIBOMP_PREFIX_DEFAULT=${LIBOMP_PREFIX:-}
GGML_GEMMINI_COMPUTE_TYPE_DEFAULT=${GGML_GEMMINI_COMPUTE_TYPE_DEFAULT:-INT} # INT | FLOAT
GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT=${GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT:-OFF} # ON | OFF; FLOAT validation mode
GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT=${GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT:-${GGML_GEMMINI_ACTIVATION_QUANT:-EXSIA}} # EXSIA | STRIPE | TENSOR | TOKEN
GGML_GEMMINI_WEIGHT_QUANT_DEFAULT=${GGML_GEMMINI_WEIGHT_QUANT_DEFAULT:-${GGML_GEMMINI_WEIGHT_QUANT:-TENSOR}} # TENSOR
GGML_GEMMINI_BLOCK_SIZE_DEFAULT=${GGML_GEMMINI_BLOCK_SIZE_DEFAULT:-${GGML_GEMMINI_BLOCK_SIZE:-32}} # 32 | 64 | 128
GGML_GEMMINI_EXSIA_SIGMA_DEFAULT=${GGML_GEMMINI_EXSIA_SIGMA:-2} # positive integer
# Matmul invocation defaults select the public FULL/STRIPE contract.
GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT=${GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT:-${GGML_GEMMINI_ENABLE_STRIPE_MATMUL:-ON}} # ON | OFF
GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT=${GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT:-${GGML_GEMMINI_ENABLE_STRIPE_PIPELINE:-ON}} # ON | OFF
GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT=${GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT:-${GGML_GEMMINI_DEFAULT_MATMUL_MODE:-STRIPE_PIPELINE}} # FULL | STRIPE_SEQUENTIAL | STRIPE_PIPELINE
GGML_GEMMINI_DEFAULT_STRIPE_ROWS_DEFAULT=${GGML_GEMMINI_DEFAULT_STRIPE_ROWS_DEFAULT:-${GGML_GEMMINI_DEFAULT_STRIPE_ROWS:-AUTO}} # AUTO | positive integer
GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT=${GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT:-${GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY:-2}} # positive integer
GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT=${GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT:-${GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE:-OFF}} # ON | OFF
GGML_GEMMINI_ENABLE_RMD_DEFAULT=${GGML_GEMMINI_ENABLE_RMD_DEFAULT:-${GGML_GEMMINI_ENABLE_RMD:-ON}} # ON | OFF
# ExSIA default mode configures internal activation staging, not the public matmul mode.
GGML_GEMMINI_EXSIA_DEFAULT_MODE_DEFAULT=${GGML_GEMMINI_EXSIA_DEFAULT_MODE:-LOCAL_FOLDING_PIPELINE} # SEQUENTIAL | LOCAL_PARALLEL | LOCAL_FOLDING_PIPELINE
GGML_GEMMINI_EXSIA_LOCAL_WORKERS_DEFAULT=${GGML_GEMMINI_EXSIA_LOCAL_WORKERS:-3} # 4
GGML_GEMMINI_EXSIA_SUPERBLOCKS_DEFAULT=${GGML_GEMMINI_EXSIA_SUPERBLOCKS:-3} # 4
GGML_GEMMINI_EXSIA_PIPELINE_SLOTS_DEFAULT=${GGML_GEMMINI_EXSIA_PIPELINE_SLOTS:-2} # 2
GGML_GEMMINI_EXSIA_OMP_THREADS_DEFAULT=${GGML_GEMMINI_EXSIA_OMP_THREADS:-4} # 5
GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT=${GGML_GEMMINI_EXSIA_PROFILE_SCOPE:-STAGE} # OFF | TIMELINE | STAGE
BREW_BIN=""

if [[ "$CYCLE_DETAIL_DEFAULT" == "1" && "$LOG_CYCLE_DEFAULT" != "1" ]]; then
  printf '%s\n' "CYCLE_DETAIL=1 requires LOG_CYCLE=1" >&2
  exit 2
fi
if [[ "$GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT" != "OFF" && "$CYCLE_DETAIL_DEFAULT" != "1" ]]; then
  printf '%s\n' "ExSIA profiling requires CYCLE_DETAIL=1" >&2
  exit 2
fi

if command -v brew >/dev/null 2>&1; then
  BREW_BIN="$(command -v brew)"
elif [[ -x "/opt/homebrew/bin/brew" ]]; then
  BREW_BIN="/opt/homebrew/bin/brew"
elif [[ -x "/usr/local/bin/brew" ]]; then
  BREW_BIN="/usr/local/bin/brew"
fi

if [[ -z "$LIBOMP_PREFIX_DEFAULT" ]] && [[ -n "$BREW_BIN" ]]; then
  if "$BREW_BIN" list libomp >/dev/null 2>&1; then
    LIBOMP_PREFIX_DEFAULT="$("$BREW_BIN" --prefix libomp)"
  fi
fi

CMAKE_PREFIX_PATH_DEFAULT="${CMAKE_PREFIX_PATH:-}"

cmake -B "$BUILD_DIR" -S . \
  -DGGML_METAL=OFF \
  -DGGML_BLAS=OFF \
  -DGGML_GEMMINI=ON \
  -DGGML_BACKEND_DL=ON \
  -DGGML_GEMMINI_FORCE_GGML_OUTPUT=OFF \
  -DGGML_GEMMINI_FORCE_GGML_ALL=OFF \
  -DLOG_DEBUG="${LOG_DEBUG_DEFAULT}" \
  -DLOG_CYCLE="${LOG_CYCLE_DEFAULT}" \
  -DGGML_CPU_CYCLE_LOG="${GGML_CPU_CYCLE_LOG_DEFAULT}" \
  -DCYCLE_DETAIL="${CYCLE_DETAIL_DEFAULT}" \
  -DLOG_DUMP="${LOG_DUMP_DEFAULT}" \
  -DLOG_DUMP_SCALE="${LOG_DUMP_SCALE_DEFAULT}" \
  -DGGML_GEMMINI_PRINT_TILE="${GGML_GEMMINI_PRINT_TILE_DEFAULT}" \
  -DGGML_GEMMINI_OPTION="${GGML_GEMMINI_OPTION_DEFAULT}" \
  -DGGML_GEMMINI_FULL_C="${GGML_GEMMINI_FULL_C_DEFAULT}" \
  -DGGML_GEMMINI_LOW_D="${GGML_GEMMINI_LOW_D_DEFAULT}" \
  -DGGML_GEMMINI_TRANSPOSE_B="${GGML_GEMMINI_TRANSPOSE_B_DEFAULT}" \
  -DGGML_GEMMINI_WS_LOOP_DEBUG="${GGML_GEMMINI_WS_LOOP_DEBUG_DEFAULT}" \
  -DGGML_GEMMINI_COMPUTE_TYPE="${GGML_GEMMINI_COMPUTE_TYPE_DEFAULT}" \
  -DGGML_GEMMINI_DEQUANT_FP_TEST="${GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT}" \
  -DGGML_GEMMINI_ACTIVATION_QUANT="${GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT}" \
  -DGGML_GEMMINI_WEIGHT_QUANT="${GGML_GEMMINI_WEIGHT_QUANT_DEFAULT}" \
  -DGGML_GEMMINI_BLOCK_SIZE="${GGML_GEMMINI_BLOCK_SIZE_DEFAULT}" \
  -DGGML_GEMMINI_EXSIA_SIGMA="${GGML_GEMMINI_EXSIA_SIGMA_DEFAULT}" \
  -DGGML_GEMMINI_ENABLE_STRIPE_MATMUL="${GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT}" \
  -DGGML_GEMMINI_ENABLE_STRIPE_PIPELINE="${GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT}" \
  -DGGML_GEMMINI_DEFAULT_MATMUL_MODE="${GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT}" \
  -DGGML_GEMMINI_DEFAULT_STRIPE_ROWS="${GGML_GEMMINI_DEFAULT_STRIPE_ROWS_DEFAULT}" \
  -DGGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY="${GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT}" \
  -DGGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE="${GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT}" \
  -DGGML_GEMMINI_ENABLE_RMD="${GGML_GEMMINI_ENABLE_RMD_DEFAULT}" \
  -DGGML_GEMMINI_EXSIA_DEFAULT_MODE="${GGML_GEMMINI_EXSIA_DEFAULT_MODE_DEFAULT}" \
  -DGGML_GEMMINI_EXSIA_LOCAL_WORKERS="${GGML_GEMMINI_EXSIA_LOCAL_WORKERS_DEFAULT}" \
  -DGGML_GEMMINI_EXSIA_SUPERBLOCKS="${GGML_GEMMINI_EXSIA_SUPERBLOCKS_DEFAULT}" \
  -DGGML_GEMMINI_EXSIA_PIPELINE_SLOTS="${GGML_GEMMINI_EXSIA_PIPELINE_SLOTS_DEFAULT}" \
  -DGGML_GEMMINI_EXSIA_OMP_THREADS_DEFAULT="${GGML_GEMMINI_EXSIA_OMP_THREADS_DEFAULT}" \
  -DGGML_GEMMINI_EXSIA_PROFILE_SCOPE="${GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT}" \
  -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE_DEFAULT}" \
  -DGGML_NATIVE="${GGML_NATIVE_DEFAULT}" \
  -DLLAMA_CURL="${LLAMA_CURL_DEFAULT}" \
  -DCMAKE_OSX_ARCHITECTURES="${APPLE_SILICON_ARCH_DEFAULT}" \
  -DGGML_OPENMP="${GGML_OPENMP_DEFAULT}" \
  -DGGML_GEMMINI_ENABLE_OPENMP="${GGML_GEMMINI_ENABLE_OPENMP_DEFAULT}" \
  ${LIBOMP_PREFIX_DEFAULT:+-DOpenMP_ROOT="${LIBOMP_PREFIX_DEFAULT}"} \
  ${LIBOMP_PREFIX_DEFAULT:+-DCMAKE_PREFIX_PATH="${LIBOMP_PREFIX_DEFAULT}${CMAKE_PREFIX_PATH_DEFAULT:+:${CMAKE_PREFIX_PATH_DEFAULT}}"} \
  "$@"

rm -f "$BUILD_DIR/bin/libggml-cpu.so" "$BUILD_DIR/bin/libggml-gemmini.so"
cmake --build "$BUILD_DIR" --target llama-cli llama-perplexity llama-quantize -j"${BUILD_JOBS_DEFAULT}"
