#!/bin/bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Build Gemmini in CPU fallback mode on Apple Silicon; outputs live in build/bin
BUILD_DIR=${BUILD_DIR:-"$script_dir/build-arm64"}
LLAMA_CURL_DEFAULT=${LLAMA_CURL_DEFAULT:-OFF} # disable libcurl requirement on local macOS unless explicitly enabled
CMAKE_BUILD_TYPE_DEFAULT=${CMAKE_BUILD_TYPE_DEFAULT:-Release} # Debug | Release
GGML_NATIVE_DEFAULT=${GGML_NATIVE_DEFAULT:-ON} # ON | OFF
LOG_DEBUG_DEFAULT=${LOG_DEBUG:-1} # 0 | 1
LOG_CYCLE_DEFAULT=${LOG_CYCLE:-1} # 0 | 1
LOG_DUMP_DEFAULT=${LOG_DUMP:-0} # 0 | 1
LOG_DUMP_SCALE_DEFAULT=${LOG_DUMP_SCALE:-0} # 0 | 1
ERROR_COMPENSATION_DEFAULT=${ERROR_COMPENSATION:-1} # 0 | 1
GGML_GEMMINI_PRINT_TILE_DEFAULT=${GGML_GEMMINI_PRINT_TILE:-0} # 0 | 1
GGML_GEMMINI_OPTION_DEFAULT=${GGML_GEMMINI_OPTION:-CPU} # CPU | OS | WS
GGML_GEMMINI_FULL_C_DEFAULT=${GGML_GEMMINI_FULL_C:-1} # 0 | 1
GGML_GEMMINI_LOW_D_DEFAULT=${GGML_GEMMINI_LOW_D:-0} # 0 | 1
GGML_GEMMINI_TRANSPOSE_B_DEFAULT=${GGML_GEMMINI_TRANSPOSE_B:-1} # 0 | 1
APPLE_SILICON_ARCH_DEFAULT=${APPLE_SILICON_ARCH:-arm64}
BUILD_JOBS_DEFAULT=${BUILD_JOBS:-$(sysctl -n hw.logicalcpu)}

cmake -B "$BUILD_DIR" -S "$script_dir" \
  -DGGML_GEMMINI=ON \
  -DGGML_GEMMINI_FORCE_GGML_OUTPUT=OFF \
  -DGGML_GEMMINI_FORCE_GGML_ALL=OFF \
  -DLOG_DEBUG="${LOG_DEBUG_DEFAULT}" \
  -DLOG_CYCLE="${LOG_CYCLE_DEFAULT}" \
  -DLOG_DUMP="${LOG_DUMP_DEFAULT}" \
  -DLOG_DUMP_SCALE="${LOG_DUMP_SCALE_DEFAULT}" \
  -DERROR_COMPENSATION="${ERROR_COMPENSATION_DEFAULT}" \
  -DGGML_GEMMINI_PRINT_TILE="${GGML_GEMMINI_PRINT_TILE_DEFAULT}" \
  -DGGML_GEMMINI_OPTION="${GGML_GEMMINI_OPTION_DEFAULT}" \
  -DGGML_GEMMINI_FULL_C="${GGML_GEMMINI_FULL_C_DEFAULT}" \
  -DGGML_GEMMINI_LOW_D="${GGML_GEMMINI_LOW_D_DEFAULT}" \
  -DGGML_GEMMINI_TRANSPOSE_B="${GGML_GEMMINI_TRANSPOSE_B_DEFAULT}" \
  -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE_DEFAULT}" \
  -DGGML_NATIVE="${GGML_NATIVE_DEFAULT}" \
  -DLLAMA_CURL="${LLAMA_CURL_DEFAULT}" \
  -DCMAKE_OSX_ARCHITECTURES="${APPLE_SILICON_ARCH_DEFAULT}" \
  "$@"

cmake --build "$BUILD_DIR" --target llama-cli llama-perplexity -j"${BUILD_JOBS_DEFAULT}"
