#!/bin/bash
set -euo pipefail

# Build Gemmini in CPU fallback mode on Apple Silicon; outputs live in build/bin
BUILD_DIR=${BUILD_DIR:-build-arm64}
LLAMA_CURL_DEFAULT=${LLAMA_CURL_DEFAULT:-OFF} # disable libcurl requirement on local macOS unless explicitly enabled
CMAKE_BUILD_TYPE_DEFAULT=${CMAKE_BUILD_TYPE_DEFAULT:-Release} # Debug | Release
GGML_NATIVE_DEFAULT=${GGML_NATIVE_DEFAULT:-ON} # ON | OFF
LOG_DEBUG_DEFAULT=${LOG_DEBUG:-0} # 0 | 1
LOG_CYCLE_DEFAULT=${LOG_CYCLE:-0} # 0 | 1
LOG_DUMP_DEFAULT=${LOG_DUMP:-0} # 0 | 1
LOG_DUMP_SCALE_DEFAULT=${LOG_DUMP_SCALE:-0} # 0 | 1
ERROR_COMPENSATION_DEFAULT=${ERROR_COMPENSATION:-1} # 0 | 1
GGML_GEMMINI_PRINT_TILE_DEFAULT=${GGML_GEMMINI_PRINT_TILE:-0} # 0 | 1
GGML_GEMMINI_OPTION_DEFAULT=${GGML_GEMMINI_OPTION:-CPU} # CPU | OS | WS
GGML_GEMMINI_FULL_C_DEFAULT=${GGML_GEMMINI_FULL_C:-1} # 0 | 1
GGML_GEMMINI_LOW_D_DEFAULT=${GGML_GEMMINI_LOW_D:-0} # 0 | 1
GGML_GEMMINI_TRANSPOSE_B_DEFAULT=${GGML_GEMMINI_TRANSPOSE_B:-1} # 0 | 1
APPLE_SILICON_ARCH_DEFAULT=${APPLE_SILICON_ARCH:-arm64}
BUILD_JOBS_DEFAULT=${BUILD_JOBS:-$(sysctl -n hw.logicalcpu)}
OPENMP_ENABLED_DEFAULT=${ORCA_ENABLE_OPENMP_DEFAULT:-ON}
LIBOMP_PREFIX_DEFAULT=${LIBOMP_PREFIX:-}
BREW_BIN=""

if command -v brew >/dev/null 2>&1; then
  BREW_BIN="$(command -v brew)"
elif [[ -x "/opt/homebrew/bin/brew" ]]; then
  BREW_BIN="/opt/homebrew/bin/brew"
elif [[ -x "/usr/local/bin/brew" ]]; then
  BREW_BIN="/usr/local/bin/brew"
fi

if [[ -z "$LIBOMP_PREFIX_DEFAULT" ]] && [[ -n "$BREW_BIN" ]]; then
  if "$BREW_BIN" list libomp >/dev/null 2>&1; then
    LIBOMP_PREFIX_DEFAULT="$("$BREW_BIN" --prefix libomp)"
  fi
fi

CMAKE_PREFIX_PATH_DEFAULT="${CMAKE_PREFIX_PATH:-}"

cmake -B "$BUILD_DIR" -S . \
  -DGGML_METAL=OFF \
  -DGGML_BLAS=OFF \
  -DGGML_GEMMINI=ON \
  -DGGML_GEMMINI_FORCE_GGML_OUTPUT=OFF \
  -DGGML_GEMMINI_FORCE_GGML_ALL=OFF \
  -DLOG_DEBUG="${LOG_DEBUG_DEFAULT}" \
  -DLOG_CYCLE="${LOG_CYCLE_DEFAULT}" \
  -DLOG_DUMP="${LOG_DUMP_DEFAULT}" \
  -DLOG_DUMP_SCALE="${LOG_DUMP_SCALE_DEFAULT}" \
  -DERROR_COMPENSATION="${ERROR_COMPENSATION_DEFAULT}" \
  -DGGML_GEMMINI_PRINT_TILE="${GGML_GEMMINI_PRINT_TILE_DEFAULT}" \
  -DGGML_GEMMINI_OPTION="${GGML_GEMMINI_OPTION_DEFAULT}" \
  -DGGML_GEMMINI_FULL_C="${GGML_GEMMINI_FULL_C_DEFAULT}" \
  -DGGML_GEMMINI_LOW_D="${GGML_GEMMINI_LOW_D_DEFAULT}" \
  -DGGML_GEMMINI_TRANSPOSE_B="${GGML_GEMMINI_TRANSPOSE_B_DEFAULT}" \
  -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE_DEFAULT}" \
  -DGGML_NATIVE="${GGML_NATIVE_DEFAULT}" \
  -DLLAMA_CURL="${LLAMA_CURL_DEFAULT}" \
  -DCMAKE_OSX_ARCHITECTURES="${APPLE_SILICON_ARCH_DEFAULT}" \
  -DGGML_OPENMP="${OPENMP_ENABLED_DEFAULT}" \
  ${LIBOMP_PREFIX_DEFAULT:+-DOpenMP_ROOT="${LIBOMP_PREFIX_DEFAULT}"} \
  ${LIBOMP_PREFIX_DEFAULT:+-DCMAKE_PREFIX_PATH="${LIBOMP_PREFIX_DEFAULT}${CMAKE_PREFIX_PATH_DEFAULT:+:${CMAKE_PREFIX_PATH_DEFAULT}}"} \
  "$@"

cmake --build "$BUILD_DIR" --target llama-cli llama-perplexity -j"${BUILD_JOBS_DEFAULT}"
