#!/bin/bash
set -euo pipefail

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/im2p-host-provision.sh
source "$SCRIPT_ROOT/scripts/im2p-host-provision.sh"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  printf 'Usage: %s [--dry-run] [-DNAME[:TYPE]=value ...]\n' "${0##*/}"
  printf '%s\n' 'Environment overrides: BUILD_DIR, BUILD_JOBS, GGML_*, IM2P_*.'
  printf '%s\n' 'GGML_GEMMINI_DIM=16|32|64 selects host tiling; IM2P_DIM is a deprecated alias.'
  exit 0
fi

# Build the selected Gemmini backend on x86; outputs live in build-x86/bin by default.
BUILD_DIR=${BUILD_DIR:-build-x86}
LLAMA_CURL_DEFAULT=${LLAMA_CURL_DEFAULT:-OFF} # disable libcurl requirement on local x86 unless explicitly enabled
CMAKE_BUILD_TYPE_DEFAULT=${CMAKE_BUILD_TYPE_DEFAULT:-Release} # Debug | Release
GGML_NATIVE_DEFAULT=${GGML_NATIVE_DEFAULT:-ON} # ON | OFF
BUILD_JOBS_DEFAULT=${BUILD_JOBS:-$(nproc)}
GGML_OPENMP_DEFAULT=${GGML_OPENMP:-ON}
GGML_GEMMINI_ENABLE_OPENMP_DEFAULT=${GGML_GEMMINI_ENABLE_OPENMP:-ON}
LOG_DEBUG_DEFAULT=${LOG_DEBUG:-1} # 0 | 1
LOG_CYCLE_DEFAULT=${LOG_CYCLE:-1} # 0 | 1
CYCLE_SIM_DEFAULT=${CYCLE_SIM:-0}
GGML_CPU_CYCLE_LOG_DEFAULT=${GGML_CPU_CYCLE_LOG:-${LOG_CYCLE_DEFAULT}}
CYCLE_DETAIL_DEFAULT=${CYCLE_DETAIL:-0} # 0 | 1
LOG_DUMP_DEFAULT=${LOG_DUMP:-0} # 0 | 1
LOG_DUMP_SCALE_DEFAULT=${LOG_DUMP_SCALE:-0} # 0 | 1
GGML_GEMMINI_PRINT_TILE_DEFAULT=${GGML_GEMMINI_PRINT_TILE:-0} # 0 | 1
GGML_GEMMINI_OPTION_DEFAULT=${GGML_GEMMINI_OPTION:-WS} # CPU | OS | WS
GGML_GEMMINI_FULL_C_DEFAULT=${GGML_GEMMINI_FULL_C:-1} # 0 | 1
GGML_GEMMINI_LOW_D_DEFAULT=${GGML_GEMMINI_LOW_D:-0} # 0 | 1
GGML_GEMMINI_TRANSPOSE_B_DEFAULT=${GGML_GEMMINI_TRANSPOSE_B:-1} # 0 | 1
GGML_GEMMINI_WS_LOOP_CYCLE_DEFAULT=${GGML_GEMMINI_WS_LOOP_CYCLE:-0} # 0 | 1
GGML_GEMMINI_COMPUTE_TYPE_DEFAULT=${GGML_GEMMINI_COMPUTE_TYPE_DEFAULT:-${GGML_GEMMINI_COMPUTE_TYPE:-INT}} # INT | FLOAT
GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT=${GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT:-${GGML_GEMMINI_DEQUANT_FP_TEST:-OFF}} # ON | OFF; FLOAT validation mode
GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT=${GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT:-${GGML_GEMMINI_ACTIVATION_QUANT:-EXSIA}} # EXSIA | TENSOR | TOKEN | BLOCK | STRIPE
GGML_GEMMINI_ACTIVATION_BITS_DEFAULT=${GGML_GEMMINI_ACTIVATION_BITS_DEFAULT:-${GGML_GEMMINI_ACTIVATION_BITS:-8}} # 4 | 8 | 16
GGML_GEMMINI_WEIGHT_BITS_DEFAULT=${GGML_GEMMINI_WEIGHT_BITS_DEFAULT:-${GGML_GEMMINI_WEIGHT_BITS:-8}} # 4 | 8 | 16
GGML_GEMMINI_EXECUTION_BACKEND_DEFAULT=${GGML_GEMMINI_EXECUTION_BACKEND:-FPGA_UART} # HARDWARE | IM2P_SIM | FPGA_UART
IM2P_SIM_IMPLEMENTATION_DEFAULT=${IM2P_SIM_IMPLEMENTATION:-GEMMINI_HP1}
IM2P_SIM_ROOT_DEFAULT=${IM2P_SIM_ROOT:-../IM2P.sim}
GGML_GEMMINI_DIM_DEFAULT=${GGML_GEMMINI_DIM:-16} # 16 | 32 | 64
GGML_GEMMINI_BLOCK_SIZE_DEFAULT=${GGML_GEMMINI_BLOCK_SIZE_DEFAULT:-${GGML_GEMMINI_BLOCK_SIZE:-32}} # 32 | 64 | 128
GGML_GEMMINI_EXSIA_SIGMA_DEFAULT=${GGML_GEMMINI_EXSIA_SIGMA:-2} # positive integer
# Public matmul invocation defaults: FULL / STRIPE_PIPELINE.
GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT=${GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT:-${GGML_GEMMINI_ENABLE_STRIPE_MATMUL:-ON}} # ON | OFF
GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT=${GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT:-${GGML_GEMMINI_ENABLE_STRIPE_PIPELINE:-ON}} # ON | OFF
GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT=${GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT:-${GGML_GEMMINI_DEFAULT_MATMUL_MODE:-STRIPE_PIPELINE}} # FULL | STRIPE_PIPELINE
GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT=${GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT:-${GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY:-2}} # positive integer
GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT=${GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT:-${GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE:-ON}} # ON | OFF
GGML_GEMMINI_ENABLE_RMD_DEFAULT=${GGML_GEMMINI_ENABLE_RMD_DEFAULT:-${GGML_GEMMINI_ENABLE_RMD:-ON}} # ON | OFF
GGML_GEMMINI_DEFAULT_RMD_BACKEND_DEFAULT=${GGML_GEMMINI_DEFAULT_RMD_BACKEND_DEFAULT:-${GGML_GEMMINI_DEFAULT_RMD_BACKEND:-WS}} # CPU | WS
# ExSIA default mode configures internal activation staging, not the public matmul mode.
GGML_GEMMINI_EXSIA_DEFAULT_MODE_DEFAULT=${GGML_GEMMINI_EXSIA_DEFAULT_MODE:-SEQUENTIAL} # SEQUENTIAL | LOCAL_PARALLEL | LOCAL_FOLDING_PIPELINE
GGML_GEMMINI_EXSIA_LOCAL_WORKERS_DEFAULT=${GGML_GEMMINI_EXSIA_LOCAL_WORKERS:-4} # 3 | 4
GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT=${GGML_GEMMINI_EXSIA_PROFILE_SCOPE:-OFF} # OFF | TIMELINE | STAGE

im2p_resolve_build_options "$BUILD_DIR" "${0##*/}" "$@"
if [[ "$IM2P_BUILD_DRY_RUN" == 1 ]]; then
  printf 'Dry run: no provisioning, configure, build, or device access.\n'
  exit 0
fi

if [[ "$CYCLE_DETAIL_DEFAULT" == "1" && "$LOG_CYCLE_DEFAULT" != "1" ]]; then
  printf '%s\n' "CYCLE_DETAIL=1 requires LOG_CYCLE=1" >&2
  exit 2
fi
if [[ "$GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT" != "OFF" && "$CYCLE_DETAIL_DEFAULT" != "1" ]]; then
  printf '%s\n' "ExSIA profiling requires CYCLE_DETAIL=1" >&2
  exit 2
fi

if [[ "$GGML_GEMMINI_EXECUTION_BACKEND_DEFAULT" == "IM2P_SIM" && "$CYCLE_SIM_DEFAULT" == 0 ]]; then
  im2p_provision_host_artifacts \
    "$IM2P_SIM_ROOT_DEFAULT" "$SCRIPT_ROOT" "$BUILD_JOBS_DEFAULT" \
    "$GGML_GEMMINI_ACTIVATION_BITS_DEFAULT" \
    "$GGML_GEMMINI_WEIGHT_BITS_DEFAULT" \
    "$GGML_GEMMINI_DIM_DEFAULT" "$GGML_GEMMINI_BLOCK_SIZE_DEFAULT" \
    "$IM2P_SIM_IMPLEMENTATION_DEFAULT"
fi

cmake -B "$BUILD_DIR" -S "$SCRIPT_ROOT" \
  -U 'GGML_*' \
  -U 'IM2P_*' \
  -U 'LLAMA_*' \
  -U 'LOG_*' \
  -U 'CYCLE_*' \
  -U 'BUILD_SHARED_LIBS' \
  -U 'CMAKE_TOOLCHAIN_FILE' \
  -U 'CMAKE_PREFIX_PATH' \
  -U 'OpenMP_ROOT' \
  "${IM2P_EFFECTIVE_CMAKE_ARGS[@]}"

cmake --build "$BUILD_DIR" --target llama-cli llama-perplexity -j"${BUILD_JOBS_DEFAULT}"
