#!/bin/bash
set -euo pipefail

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/im2p-host-provision.sh
source "$SCRIPT_ROOT/scripts/im2p-host-provision.sh"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  printf 'Usage: %s [--dry-run] [-DNAME[:TYPE]=value ...]\n' "${0##*/}"
  printf '%s\n' 'Environment overrides: BUILD_DIR, BUILD_JOBS, GGML_*, IM2P_*.'
  printf '%s\n' 'GGML_GEMMINI_DIM=16|32|64 selects host tiling and the matching IM2P artifact; IM2P_DIM is a deprecated alias.'
  exit 0
fi

# Build the selected Gemmini backend on ARM64 (Linux or macOS); outputs live in build-arm64/bin by default.

# Shell controls; these are not CMake cache defaults.
BUILD_DIR=${BUILD_DIR:-${BUILD_DIR_DEFAULT:-build-arm64-cpu}}
BUILD_JOBS_DEFAULT=${BUILD_JOBS:-${BUILD_JOBS_DEFAULT:-$(im2p_host_jobs)}}
IM2P_ARTIFACT_SET_DEFAULT=${IM2P_ARTIFACT_SET_DEFAULT:-SELECTED}
IM2P_CACHE_JOBS_DEFAULT=${IM2P_CACHE_JOBS_DEFAULT:-}
APPLE_SILICON_ARCH_DEFAULT=${APPLE_SILICON_ARCH_DEFAULT:-arm64}
LIBOMP_PREFIX_DEFAULT=${LIBOMP_PREFIX_DEFAULT:-}

# Backend and platform policy.
GGML_GEMMINI_DEFAULT=${GGML_GEMMINI_DEFAULT:-ON}
GGML_GEMMINI_EXECUTION_BACKEND_DEFAULT=${GGML_GEMMINI_EXECUTION_BACKEND_DEFAULT:-HARDWARE}
GGML_GEMMINI_OPTION_DEFAULT=${GGML_GEMMINI_OPTION_DEFAULT:-CPU}
GEMMINI_SW_PATH_DEFAULT=${GEMMINI_SW_PATH_DEFAULT:-"$SCRIPT_ROOT/../RISC-V-DynDNN-gemmini-include"}
GGML_NATIVE_DEFAULT=${GGML_NATIVE_DEFAULT:-ON}
GGML_OPENMP_DEFAULT=${GGML_OPENMP_DEFAULT:-ON}
GGML_GEMMINI_ENABLE_OPENMP_DEFAULT=${GGML_GEMMINI_ENABLE_OPENMP_DEFAULT:-ON}
GGML_CUDA_DEFAULT=${GGML_CUDA_DEFAULT:-OFF}
GGML_BACKEND_DL_DEFAULT=${GGML_BACKEND_DL_DEFAULT:-ON}
LLAMA_BUILD_TESTS_DEFAULT=${LLAMA_BUILD_TESTS_DEFAULT:-OFF}
LLAMA_CURL_DEFAULT=${LLAMA_CURL_DEFAULT:-OFF}
CMAKE_BUILD_TYPE_DEFAULT=${CMAKE_BUILD_TYPE_DEFAULT:-Release}
BUILD_SHARED_LIBS_DEFAULT=${BUILD_SHARED_LIBS_DEFAULT:-ON}
GGML_METAL_DEFAULT=${GGML_METAL_DEFAULT:-OFF}
GGML_BLAS_DEFAULT=${GGML_BLAS_DEFAULT:-OFF}
if [[ "$(uname -s)" == Darwin ]]; then
  LIBOMP_PREFIX_DEFAULT=${LIBOMP_PREFIX:-${LIBOMP_PREFIX_DEFAULT:-$(im2p_host_libomp_prefix)}}
  CMAKE_OSX_ARCHITECTURES_DEFAULT=${CMAKE_OSX_ARCHITECTURES_DEFAULT:-"${APPLE_SILICON_ARCH:-$APPLE_SILICON_ARCH_DEFAULT}"}
  if [[ -n "$LIBOMP_PREFIX_DEFAULT" ]]; then
    OpenMP_ROOT_DEFAULT=${OpenMP_ROOT_DEFAULT:-"$LIBOMP_PREFIX_DEFAULT"}
    CMAKE_PREFIX_PATH_DEFAULT=${CMAKE_PREFIX_PATH_DEFAULT:-"$LIBOMP_PREFIX_DEFAULT"}
  fi
fi

# Geometry and precision.
GGML_GEMMINI_COMPUTE_TYPE_DEFAULT=${GGML_GEMMINI_COMPUTE_TYPE_DEFAULT:-INT}
GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT=${GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT:-OFF}
GGML_GEMMINI_ACTIVATION_BITS_DEFAULT=${GGML_GEMMINI_ACTIVATION_BITS_DEFAULT:-8}
GGML_GEMMINI_WEIGHT_BITS_DEFAULT=${GGML_GEMMINI_WEIGHT_BITS_DEFAULT:-8}
GGML_GEMMINI_DIM_DEFAULT=${GGML_GEMMINI_DIM_DEFAULT:-64}
GGML_GEMMINI_BLOCK_SIZE_DEFAULT=${GGML_GEMMINI_BLOCK_SIZE_DEFAULT:-32}
GGML_GEMMINI_PRINT_TILE_DEFAULT=${GGML_GEMMINI_PRINT_TILE_DEFAULT:-0}
GGML_GEMMINI_FULL_C_DEFAULT=${GGML_GEMMINI_FULL_C_DEFAULT:-1}
GGML_GEMMINI_LOW_D_DEFAULT=${GGML_GEMMINI_LOW_D_DEFAULT:-0}
GGML_GEMMINI_TRANSPOSE_B_DEFAULT=${GGML_GEMMINI_TRANSPOSE_B_DEFAULT:-1}
GGML_GEMMINI_WS_DEBUG_DEFAULT=${GGML_GEMMINI_WS_DEBUG_DEFAULT:-0}
GGML_GEMMINI_WS_LOOP_CYCLE_DEFAULT=${GGML_GEMMINI_WS_LOOP_CYCLE_DEFAULT:-0}
GGML_GEMMINI_DISABLE_WS_REUSE_DEFAULT=${GGML_GEMMINI_DISABLE_WS_REUSE_DEFAULT:-0}

# Matmul and residual execution.
GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT=${GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT:-ON}
GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT=${GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT:-ON}
GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT=${GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT:-STRIPE_PIPELINE}
GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT=${GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT:-2}
GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT=${GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT:-OFF}
GGML_GEMMINI_ENABLE_RMD_DEFAULT=${GGML_GEMMINI_ENABLE_RMD_DEFAULT:-ON}
GGML_GEMMINI_DEFAULT_RMD_BACKEND_DEFAULT=${GGML_GEMMINI_DEFAULT_RMD_BACKEND_DEFAULT:-CPU}

# ExSIA activation staging.
GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT=${GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT:-EXSIA}
GGML_GEMMINI_EXSIA_SIGMA_DEFAULT=${GGML_GEMMINI_EXSIA_SIGMA_DEFAULT:-2}
GGML_GEMMINI_EXSIA_DEFAULT_MODE_DEFAULT=${GGML_GEMMINI_EXSIA_DEFAULT_MODE_DEFAULT:-LOCAL_FOLDING_PIPELINE}
GGML_GEMMINI_EXSIA_LOCAL_WORKERS_DEFAULT=${GGML_GEMMINI_EXSIA_LOCAL_WORKERS_DEFAULT:-3}
GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT=${GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT:-OFF}

# Logs and independent metrics. CPU logging follows final LOG_CYCLE unless overridden.
LOG_DEBUG_DEFAULT=${LOG_DEBUG_DEFAULT:-1}
LOG_CYCLE_DEFAULT=${LOG_CYCLE_DEFAULT:-1}
LOG_DUMP_DEFAULT=${LOG_DUMP_DEFAULT:-0}
LOG_DUMP_SCALE_DEFAULT=${LOG_DUMP_SCALE_DEFAULT:-0}
CYCLE_DETAIL_DEFAULT=${CYCLE_DETAIL_DEFAULT:-1}
CYCLE_SIM_DEFAULT=${CYCLE_SIM_DEFAULT:-0}
GGML_CPU_CYCLE_LOG_DEFAULT=${GGML_CPU_CYCLE_LOG_DEFAULT:-$LOG_CYCLE_DEFAULT}
GGML_GEMMINI_ACT_QUANT_METRICS_DEFAULT=${GGML_GEMMINI_ACT_QUANT_METRICS_DEFAULT:-0}
GGML_GEMMINI_RESIDUAL_METRICS_DEFAULT=${GGML_GEMMINI_RESIDUAL_METRICS_DEFAULT:-0}
GGML_GEMMINI_SCALE_METRICS_DEFAULT=${GGML_GEMMINI_SCALE_METRICS_DEFAULT:-0}

# Simulator selection; an empty cache path derives from the final simulator root.
IM2P_SIM_ROOT_DEFAULT=${IM2P_SIM_ROOT_DEFAULT:-"$SCRIPT_ROOT/../IM2P.sim"}
IM2P_SIM_BUILD_DIR_DEFAULT=${IM2P_SIM_BUILD_DIR_DEFAULT:-}
IM2P_SIM_IMPLEMENTATION_DEFAULT=${IM2P_SIM_IMPLEMENTATION_DEFAULT:-GEMMINI_HP1}

im2p_resolve_build_options "$BUILD_DIR" "${0##*/}" "$@"
if [[ "$IM2P_BUILD_DRY_RUN" == 1 ]]; then
  printf 'Dry run: no provisioning, configure, build, or device access.\n'
  exit 0
fi

if [[ "$GGML_GEMMINI_EXECUTION_BACKEND_DEFAULT" == IM2P_SIM && "$CYCLE_SIM_DEFAULT" == 0 ]]; then
  im2p_provision_host_artifacts \
    "$IM2P_SIM_ROOT_DEFAULT" "$SCRIPT_ROOT" "$BUILD_JOBS_DEFAULT" \
    "$GGML_GEMMINI_ACTIVATION_BITS_DEFAULT" \
    "$GGML_GEMMINI_WEIGHT_BITS_DEFAULT" \
    "$GGML_GEMMINI_DIM_DEFAULT" "$GGML_GEMMINI_BLOCK_SIZE_DEFAULT" \
    "$IM2P_SIM_IMPLEMENTATION_DEFAULT"
fi

im2p_configure_build "$BUILD_DIR" "${IM2P_EFFECTIVE_CMAKE_ARGS[@]}"
cmake --build "$BUILD_DIR" --target llama-cli llama-perplexity llama-quantize -j"${BUILD_JOBS_DEFAULT}"
