#!/bin/bash
set -euo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  printf 'Usage: %s [CMake configure arguments...]\n' "${0##*/}"
  printf '%s\n' 'Environment overrides: BUILD_DIR, BUILD_JOBS, GGML_*, IM2P_*.'
  exit 0
fi

# Build Gemmini in CPU fallback mode on x86; outputs live in build-x86/bin by default.
BUILD_DIR=${BUILD_DIR:-build-x86}
LLAMA_CURL_DEFAULT=${LLAMA_CURL_DEFAULT:-OFF} # disable libcurl requirement on local x86 unless explicitly enabled
CMAKE_BUILD_TYPE_DEFAULT=${CMAKE_BUILD_TYPE_DEFAULT:-Release} # Debug | Release
GGML_NATIVE_DEFAULT=${GGML_NATIVE_DEFAULT:-ON} # ON | OFF
BUILD_JOBS_DEFAULT=${BUILD_JOBS:-$(nproc)}
GGML_OPENMP_DEFAULT=${GGML_OPENMP:-ON}
GGML_GEMMINI_ENABLE_OPENMP_DEFAULT=${GGML_GEMMINI_ENABLE_OPENMP:-ON}
LOG_DEBUG_DEFAULT=${LOG_DEBUG:-0} # 0 | 1
LOG_CYCLE_DEFAULT=${LOG_CYCLE:-0} # 0 | 1
GGML_CPU_CYCLE_LOG_DEFAULT=${GGML_CPU_CYCLE_LOG:-${LOG_CYCLE_DEFAULT}}
CYCLE_DETAIL_DEFAULT=${CYCLE_DETAIL:-0} # 0 | 1
LOG_DUMP_DEFAULT=${LOG_DUMP:-0} # 0 | 1
LOG_DUMP_SCALE_DEFAULT=${LOG_DUMP_SCALE:-0} # 0 | 1
GGML_GEMMINI_PRINT_TILE_DEFAULT=${GGML_GEMMINI_PRINT_TILE:-0} # 0 | 1
GGML_GEMMINI_OPTION_DEFAULT=${GGML_GEMMINI_OPTION:-CPU} # CPU | OS | WS
GGML_GEMMINI_FULL_C_DEFAULT=${GGML_GEMMINI_FULL_C:-1} # 0 | 1
GGML_GEMMINI_LOW_D_DEFAULT=${GGML_GEMMINI_LOW_D:-0} # 0 | 1
GGML_GEMMINI_TRANSPOSE_B_DEFAULT=${GGML_GEMMINI_TRANSPOSE_B:-1} # 0 | 1
GGML_GEMMINI_WS_LOOP_DEBUG_DEFAULT=${GGML_GEMMINI_WS_LOOP_DEBUG:-0} # 0 | 1
GGML_GEMMINI_COMPUTE_TYPE_DEFAULT=${GGML_GEMMINI_COMPUTE_TYPE_DEFAULT:-${GGML_GEMMINI_COMPUTE_TYPE:-INT}} # INT | FLOAT
GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT=${GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT:-${GGML_GEMMINI_DEQUANT_FP_TEST:-OFF}} # ON | OFF; FLOAT validation mode
GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT=${GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT:-${GGML_GEMMINI_ACTIVATION_QUANT:-EXSIA}} # EXSIA | TENSOR | TOKEN | BLOCK | STRIPE
GGML_GEMMINI_ACTIVATION_BITS_DEFAULT=${GGML_GEMMINI_ACTIVATION_BITS_DEFAULT:-${GGML_GEMMINI_ACTIVATION_BITS:-8}} # 4 | 8 | 16
GGML_GEMMINI_WEIGHT_BITS_DEFAULT=${GGML_GEMMINI_WEIGHT_BITS_DEFAULT:-${GGML_GEMMINI_WEIGHT_BITS:-8}} # 4 | 8 | 16
GGML_GEMMINI_EXECUTION_BACKEND_DEFAULT=${GGML_GEMMINI_EXECUTION_BACKEND:-HARDWARE} # HARDWARE | IM2P_SIM
IM2P_SIM_ROOT_DEFAULT=${IM2P_SIM_ROOT:-}
IM2P_DIM_DEFAULT=${IM2P_DIM:-16} # 16 | 32 | 64
GGML_GEMMINI_BLOCK_SIZE_DEFAULT=${GGML_GEMMINI_BLOCK_SIZE_DEFAULT:-${GGML_GEMMINI_BLOCK_SIZE:-32}} # 32 | 64 | 128
GGML_GEMMINI_EXSIA_SIGMA_DEFAULT=${GGML_GEMMINI_EXSIA_SIGMA:-2} # positive integer
# Public matmul invocation defaults: FULL / STRIPE_PIPELINE.
GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT=${GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT:-${GGML_GEMMINI_ENABLE_STRIPE_MATMUL:-ON}} # ON | OFF
GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT=${GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT:-${GGML_GEMMINI_ENABLE_STRIPE_PIPELINE:-ON}} # ON | OFF
GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT=${GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT:-${GGML_GEMMINI_DEFAULT_MATMUL_MODE:-FULL}} # FULL | STRIPE_PIPELINE
GGML_GEMMINI_DEFAULT_STRIPE_ROWS_DEFAULT=${GGML_GEMMINI_DEFAULT_STRIPE_ROWS_DEFAULT:-${GGML_GEMMINI_DEFAULT_STRIPE_ROWS:-AUTO}} # AUTO | positive integer
GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT=${GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT:-${GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY:-2}} # positive integer
GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT=${GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT:-${GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE:-ON}} # ON | OFF
GGML_GEMMINI_ENABLE_RMD_DEFAULT=${GGML_GEMMINI_ENABLE_RMD_DEFAULT:-${GGML_GEMMINI_ENABLE_RMD:-ON}} # ON | OFF
GGML_GEMMINI_DEFAULT_RMD_BACKEND_DEFAULT=${GGML_GEMMINI_DEFAULT_RMD_BACKEND_DEFAULT:-${GGML_GEMMINI_DEFAULT_RMD_BACKEND:-CPU}} # CPU | WS
# ExSIA default mode configures internal activation staging, not the public matmul mode.
GGML_GEMMINI_EXSIA_DEFAULT_MODE_DEFAULT=${GGML_GEMMINI_EXSIA_DEFAULT_MODE:-SEQUENTIAL} # SEQUENTIAL | LOCAL_PARALLEL | LOCAL_FOLDING_PIPELINE
GGML_GEMMINI_EXSIA_LOCAL_WORKERS_DEFAULT=${GGML_GEMMINI_EXSIA_LOCAL_WORKERS:-4} # 3 | 4
GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT=${GGML_GEMMINI_EXSIA_PROFILE_SCOPE:-OFF} # OFF | TIMELINE | STAGE

if [[ "$CYCLE_DETAIL_DEFAULT" == "1" && "$LOG_CYCLE_DEFAULT" != "1" ]]; then
  printf '%s\n' "CYCLE_DETAIL=1 requires LOG_CYCLE=1" >&2
  exit 2
fi
if [[ "$GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT" != "OFF" && "$CYCLE_DETAIL_DEFAULT" != "1" ]]; then
  printf '%s\n' "ExSIA profiling requires CYCLE_DETAIL=1" >&2
  exit 2
fi

cmake -B "$BUILD_DIR" -S . \
  -DGGML_GEMMINI=ON \
  -DLOG_DEBUG="${LOG_DEBUG_DEFAULT}" \
  -DLOG_CYCLE="${LOG_CYCLE_DEFAULT}" \
  -DGGML_CPU_CYCLE_LOG="${GGML_CPU_CYCLE_LOG_DEFAULT}" \
  -DCYCLE_DETAIL="${CYCLE_DETAIL_DEFAULT}" \
  -DLOG_DUMP="${LOG_DUMP_DEFAULT}" \
  -DLOG_DUMP_SCALE="${LOG_DUMP_SCALE_DEFAULT}" \
  -DGGML_GEMMINI_PRINT_TILE="${GGML_GEMMINI_PRINT_TILE_DEFAULT}" \
  -DGGML_GEMMINI_OPTION="${GGML_GEMMINI_OPTION_DEFAULT}" \
  -DGGML_GEMMINI_FULL_C="${GGML_GEMMINI_FULL_C_DEFAULT}" \
  -DGGML_GEMMINI_LOW_D="${GGML_GEMMINI_LOW_D_DEFAULT}" \
  -DGGML_GEMMINI_TRANSPOSE_B="${GGML_GEMMINI_TRANSPOSE_B_DEFAULT}" \
  -DGGML_GEMMINI_WS_LOOP_DEBUG="${GGML_GEMMINI_WS_LOOP_DEBUG_DEFAULT}" \
  -DGGML_GEMMINI_COMPUTE_TYPE="${GGML_GEMMINI_COMPUTE_TYPE_DEFAULT}" \
  -DGGML_GEMMINI_DEQUANT_FP_TEST="${GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT}" \
  -DGGML_GEMMINI_ACTIVATION_QUANT="${GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT}" \
  -DGGML_GEMMINI_ACTIVATION_BITS="${GGML_GEMMINI_ACTIVATION_BITS_DEFAULT}" \
  -DGGML_GEMMINI_WEIGHT_BITS="${GGML_GEMMINI_WEIGHT_BITS_DEFAULT}" \
  -DGGML_GEMMINI_EXECUTION_BACKEND="${GGML_GEMMINI_EXECUTION_BACKEND_DEFAULT}" \
  -DIM2P_SIM_ROOT="${IM2P_SIM_ROOT_DEFAULT}" \
  -DIM2P_DIM="${IM2P_DIM_DEFAULT}" \
  -DGGML_GEMMINI_BLOCK_SIZE="${GGML_GEMMINI_BLOCK_SIZE_DEFAULT}" \
  -DGGML_GEMMINI_EXSIA_SIGMA="${GGML_GEMMINI_EXSIA_SIGMA_DEFAULT}" \
  -DGGML_GEMMINI_ENABLE_STRIPE_MATMUL="${GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT}" \
  -DGGML_GEMMINI_ENABLE_STRIPE_PIPELINE="${GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT}" \
  -DGGML_GEMMINI_DEFAULT_MATMUL_MODE="${GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT}" \
  -DGGML_GEMMINI_DEFAULT_STRIPE_ROWS="${GGML_GEMMINI_DEFAULT_STRIPE_ROWS_DEFAULT}" \
  -DGGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY="${GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT}" \
  -DGGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE="${GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT}" \
  -DGGML_GEMMINI_ENABLE_RMD="${GGML_GEMMINI_ENABLE_RMD_DEFAULT}" \
  -DGGML_GEMMINI_DEFAULT_RMD_BACKEND="${GGML_GEMMINI_DEFAULT_RMD_BACKEND_DEFAULT}" \
  -DGGML_GEMMINI_EXSIA_DEFAULT_MODE="${GGML_GEMMINI_EXSIA_DEFAULT_MODE_DEFAULT}" \
  -DGGML_GEMMINI_EXSIA_LOCAL_WORKERS="${GGML_GEMMINI_EXSIA_LOCAL_WORKERS_DEFAULT}" \
  -DGGML_GEMMINI_EXSIA_PROFILE_SCOPE="${GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT}" \
  -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE_DEFAULT}" \
  -DGGML_NATIVE="${GGML_NATIVE_DEFAULT}" \
  -DLLAMA_CURL="${LLAMA_CURL_DEFAULT}" \
  -DGGML_OPENMP="${GGML_OPENMP_DEFAULT}" \
  -DGGML_GEMMINI_ENABLE_OPENMP="${GGML_GEMMINI_ENABLE_OPENMP_DEFAULT}" \
  "$@"

cmake --build "$BUILD_DIR" --target llama-cli llama-perplexity -j"${BUILD_JOBS_DEFAULT}"
