#!/bin/bash

set -euo pipefail
SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_ROOT/scripts/im2p-host-provision.sh"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ||
      "${2:-}" == "-h" || "${2:-}" == "--help" ]]; then
  printf 'Usage: %s [static] [--dry-run] [-DNAME[:TYPE]=value ...]\n' "${0##*/}"
  printf '%s\n' 'Environment overrides: BUILD_DIR, GGML_*.'
  printf '%s\n' 'GGML_GEMMINI_DIM=16|32|64 must match the physical Gemmini header.'
  exit 0
fi

target=riscv
if [[ "${1:-}" == static ]]; then
  target=riscv-static
  shift
fi

# Shell controls; these are not CMake cache defaults.
BUILD_DIR=${BUILD_DIR:-${BUILD_DIR_DEFAULT:-build-$target}}
BUILD_JOBS_DEFAULT=${BUILD_JOBS:-${BUILD_JOBS_DEFAULT:-$(im2p_host_jobs)}}
IM2P_ARTIFACT_SET_DEFAULT=${IM2P_ARTIFACT_SET_DEFAULT:-SELECTED}
IM2P_CACHE_JOBS_DEFAULT=${IM2P_CACHE_JOBS_DEFAULT:-}

# Backend and platform policy.
GGML_GEMMINI_DEFAULT=${GGML_GEMMINI_DEFAULT:-ON}
GGML_GEMMINI_EXECUTION_BACKEND_DEFAULT=${GGML_GEMMINI_EXECUTION_BACKEND_DEFAULT:-HARDWARE}
GGML_GEMMINI_OPTION_DEFAULT=${GGML_GEMMINI_OPTION_DEFAULT:-WS}
GEMMINI_SW_PATH_DEFAULT=${GEMMINI_SW_PATH_DEFAULT:-"$SCRIPT_ROOT/../RISC-V-DynDNN-gemmini-include"}
GGML_NATIVE_DEFAULT=${GGML_NATIVE_DEFAULT:-OFF}
GGML_OPENMP_DEFAULT=${GGML_OPENMP_DEFAULT:-OFF}
GGML_GEMMINI_ENABLE_OPENMP_DEFAULT=${GGML_GEMMINI_ENABLE_OPENMP_DEFAULT:-ON}
GGML_CUDA_DEFAULT=${GGML_CUDA_DEFAULT:-OFF}
GGML_BACKEND_DL_DEFAULT=${GGML_BACKEND_DL_DEFAULT:-OFF}
LLAMA_BUILD_TESTS_DEFAULT=${LLAMA_BUILD_TESTS_DEFAULT:-ON}
LLAMA_CURL_DEFAULT=${LLAMA_CURL_DEFAULT:-OFF}
GGML_METAL_DEFAULT=${GGML_METAL_DEFAULT:-OFF}
GGML_BLAS_DEFAULT=${GGML_BLAS_DEFAULT:-OFF}
CMAKE_TOOLCHAIN_FILE_DEFAULT=${CMAKE_TOOLCHAIN_FILE_DEFAULT:-"$SCRIPT_ROOT/cmake/$target.cmake"}
if [[ "$target" == riscv-static ]]; then
  CMAKE_BUILD_TYPE_DEFAULT=${CMAKE_BUILD_TYPE_DEFAULT:-DEBUG}
  BUILD_SHARED_LIBS_DEFAULT=${BUILD_SHARED_LIBS_DEFAULT:-OFF}
else
  CMAKE_BUILD_TYPE_DEFAULT=${CMAKE_BUILD_TYPE_DEFAULT:-Release}
  BUILD_SHARED_LIBS_DEFAULT=${BUILD_SHARED_LIBS_DEFAULT:-ON}
fi

# Geometry and precision.
GGML_GEMMINI_COMPUTE_TYPE_DEFAULT=${GGML_GEMMINI_COMPUTE_TYPE_DEFAULT:-INT}
GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT=${GGML_GEMMINI_DEQUANT_FP_TEST_DEFAULT:-OFF}
GGML_GEMMINI_ACTIVATION_BITS_DEFAULT=${GGML_GEMMINI_ACTIVATION_BITS_DEFAULT:-8}
GGML_GEMMINI_WEIGHT_BITS_DEFAULT=${GGML_GEMMINI_WEIGHT_BITS_DEFAULT:-8}
GGML_GEMMINI_DIM_DEFAULT=${GGML_GEMMINI_DIM_DEFAULT:-16}
GGML_GEMMINI_BLOCK_SIZE_DEFAULT=${GGML_GEMMINI_BLOCK_SIZE_DEFAULT:-32}
GGML_GEMMINI_PRINT_TILE_DEFAULT=${GGML_GEMMINI_PRINT_TILE_DEFAULT:-0}
GGML_GEMMINI_FULL_C_DEFAULT=${GGML_GEMMINI_FULL_C_DEFAULT:-1}
GGML_GEMMINI_LOW_D_DEFAULT=${GGML_GEMMINI_LOW_D_DEFAULT:-0}
GGML_GEMMINI_TRANSPOSE_B_DEFAULT=${GGML_GEMMINI_TRANSPOSE_B_DEFAULT:-1}
GGML_GEMMINI_WS_DEBUG_DEFAULT=${GGML_GEMMINI_WS_DEBUG_DEFAULT:-0}
GGML_GEMMINI_WS_LOOP_CYCLE_DEFAULT=${GGML_GEMMINI_WS_LOOP_CYCLE_DEFAULT:-0}
GGML_GEMMINI_DISABLE_WS_REUSE_DEFAULT=${GGML_GEMMINI_DISABLE_WS_REUSE_DEFAULT:-0}

# Matmul and residual execution.
GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT=${GGML_GEMMINI_ENABLE_STRIPE_MATMUL_DEFAULT:-ON}
GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT=${GGML_GEMMINI_ENABLE_STRIPE_PIPELINE_DEFAULT:-ON}
GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT=${GGML_GEMMINI_DEFAULT_MATMUL_MODE_DEFAULT:-FULL}
GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT=${GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY_DEFAULT:-2}
GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT=${GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE_DEFAULT:-ON}
GGML_GEMMINI_ENABLE_RMD_DEFAULT=${GGML_GEMMINI_ENABLE_RMD_DEFAULT:-ON}
GGML_GEMMINI_DEFAULT_RMD_BACKEND_DEFAULT=${GGML_GEMMINI_DEFAULT_RMD_BACKEND_DEFAULT:-WS}

# ExSIA activation staging.
GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT=${GGML_GEMMINI_ACTIVATION_QUANT_DEFAULT:-EXSIA}
GGML_GEMMINI_EXSIA_SIGMA_DEFAULT=${GGML_GEMMINI_EXSIA_SIGMA_DEFAULT:-2}
GGML_GEMMINI_EXSIA_DEFAULT_MODE_DEFAULT=${GGML_GEMMINI_EXSIA_DEFAULT_MODE_DEFAULT:-SEQUENTIAL}
GGML_GEMMINI_EXSIA_LOCAL_WORKERS_DEFAULT=${GGML_GEMMINI_EXSIA_LOCAL_WORKERS_DEFAULT:-4}
GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT=${GGML_GEMMINI_EXSIA_PROFILE_SCOPE_DEFAULT:-OFF}

# Logs and independent metrics. CPU logging follows final LOG_CYCLE unless overridden.
LOG_DEBUG_DEFAULT=${LOG_DEBUG_DEFAULT:-0}
LOG_CYCLE_DEFAULT=${LOG_CYCLE_DEFAULT:-0}
LOG_DUMP_DEFAULT=${LOG_DUMP_DEFAULT:-0}
LOG_DUMP_SCALE_DEFAULT=${LOG_DUMP_SCALE_DEFAULT:-0}
CYCLE_DETAIL_DEFAULT=${CYCLE_DETAIL_DEFAULT:-0}
CYCLE_SIM_DEFAULT=${CYCLE_SIM_DEFAULT:-0}
GGML_CPU_CYCLE_LOG_DEFAULT=${GGML_CPU_CYCLE_LOG_DEFAULT:-$LOG_CYCLE_DEFAULT}
GGML_GEMMINI_ACT_QUANT_METRICS_DEFAULT=${GGML_GEMMINI_ACT_QUANT_METRICS_DEFAULT:-0}
GGML_GEMMINI_RESIDUAL_METRICS_DEFAULT=${GGML_GEMMINI_RESIDUAL_METRICS_DEFAULT:-0}
GGML_GEMMINI_SCALE_METRICS_DEFAULT=${GGML_GEMMINI_SCALE_METRICS_DEFAULT:-0}

# Simulator selection; an empty cache path derives from the final simulator root.
IM2P_SIM_ROOT_DEFAULT=${IM2P_SIM_ROOT_DEFAULT:-"$SCRIPT_ROOT/../IM2P.sim"}
IM2P_SIM_BUILD_DIR_DEFAULT=${IM2P_SIM_BUILD_DIR_DEFAULT:-}
IM2P_SIM_IMPLEMENTATION_DEFAULT=${IM2P_SIM_IMPLEMENTATION_DEFAULT:-GEMMINI_HP1}

im2p_resolve_build_options "$BUILD_DIR" "${0##*/}" "$@"
if [[ "$IM2P_ARTIFACT_SET_DEFAULT" == ALL_MATCHED && "$CYCLE_SIM_DEFAULT" == 0 ]]; then
  printf '%s\n' 'IM2P_ARTIFACT_SET=ALL_MATCHED is host-only; build-riscv.sh is hardware-only' >&2
  exit 2
fi
if [[ "$IM2P_BUILD_DRY_RUN" == 1 ]]; then
  printf 'Dry run: no provisioning, configure, build, or device access.\n'
  exit 0
fi

im2p_configure_build "$BUILD_DIR" "${IM2P_EFFECTIVE_CMAKE_ARGS[@]}"
cmake --build "$BUILD_DIR" --target llama-cli -j"${BUILD_JOBS_DEFAULT}"
