if(NOT DEFINED TEST_BINARY OR NOT DEFINED TEST_ROOT OR NOT DEFINED TEST_DIM)
    message(FATAL_ERROR "TEST_BINARY, TEST_ROOT, and TEST_DIM are required")
endif()
math(EXPR expected_publications "2")
set(expected_rows 1024)

file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}")

execute_process(
    COMMAND "${TEST_BINARY}" --case pipeline
    WORKING_DIRECTORY "${TEST_ROOT}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR
        "Pipeline cycle fixture failed (${result})\nstdout:\n${output}\nstderr:\n${error}")
endif()

set(cycle_path "${TEST_ROOT}/output/log/cycle-log.jsonl")
if(NOT EXISTS "${cycle_path}")
    message(FATAL_ERROR "Pipeline cycle fixture did not create ${cycle_path}")
endif()
file(READ "${cycle_path}" cycle_log)

string(REPLACE "\n" ";" cycle_rows "${cycle_log}")
set(aggregate_count 0)
set(stripe_count 0)
set(quantization_count 0)
set(aggregate_run_id "")
set(target_run_id "")
set(previous_row_end 0)
set(stripe_keys "")
set(quantization_keys "")
set(npu_count 0)
set(execution_id "")
set(lifecycle_events "")
set(lifecycle_sequence 0)
set(caller_start "")
set(caller_end "")
set(quantization_starts "")
set(quantization_ends "")
set(session_finished OFF)
foreach(row IN LISTS cycle_rows)
    if(row STREQUAL "")
        continue()
    endif()
    string(JSON record_type ERROR_VARIABLE json_error GET "${row}" record_type)
    if(json_error)
        message(FATAL_ERROR "Pipeline cycle sink contains malformed JSON: ${row}")
    endif()
    string(JSON version GET "${row}" version)
    if(NOT version EQUAL 2)
        message(FATAL_ERROR "Pipeline cycle sink contains non-v2 row: ${row}")
    endif()
    if(record_type STREQUAL "INFERENCE_EVENT")
        string(JSON event GET "${row}" event)
        string(JSON sequence GET "${row}" event_sequence)
        math(EXPR lifecycle_sequence "${lifecycle_sequence} + 1")
        if(NOT sequence EQUAL lifecycle_sequence)
            message(FATAL_ERROR "Missing or unordered lifecycle events: ${row}")
        endif()
        list(APPEND lifecycle_events "${event}")
        string(JSON current_execution GET "${row}" execution_id)
        if(execution_id STREQUAL "")
            set(execution_id "${current_execution}")
        elseif(NOT current_execution STREQUAL execution_id)
            message(FATAL_ERROR "Mixed execution identities in lifecycle records")
        endif()
        if(event STREQUAL "session_end")
            set(session_finished ON)
        endif()
        continue()
    elseif(record_type STREQUAL "RESOURCE_SAMPLE")
        string(JSON kind GET "${row}" kind)
        if(kind STREQUAL "npu")
            string(JSON backend GET "${row}" backend)
            string(JSON domain GET "${row}" domain)
            string(JSON metric GET "${row}" metric)
            string(JSON collected GET "${row}" collected)
            string(JSON npu_cycles GET "${row}" cycles)
            string(JSON resource_execution GET "${row}" execution_id)
            string(JSON request_id GET "${row}" inference_context request_id)
            string(JSON operation_id GET "${row}" inference_context operation_id)
            if(NOT backend STREQUAL "im2p_sim" OR NOT domain STREQUAL "dense" OR
               NOT metric STREQUAL "work_total_cycles" OR NOT collected OR
               NOT request_id EQUAL 1 OR NOT operation_id EQUAL 1 OR
               NOT resource_execution STREQUAL execution_id)
                message(FATAL_ERROR "Unexpected canonical NPU resource: ${row}")
            endif()
            math(EXPR npu_count "${npu_count} + 1")
        endif()
        continue()
    endif()
    string(JSON op ERROR_VARIABLE op_error GET "${row}" op)
    if(op_error)
        continue()
    endif()
    if(op STREQUAL "gemmini.quantize_activation")
        string(JSON operation_id ERROR_VARIABLE context_error GET "${row}" inference_context operation_id)
        if(NOT context_error AND operation_id EQUAL 1)
            string(JSON caller_start GET "${row}" host_timing start_ns)
            string(JSON caller_end GET "${row}" host_timing end_ns)
            string(JSON caller_execution GET "${row}" host_timing execution_id)
            string(JSON additive GET "${row}" additive)
            if(caller_end LESS caller_start OR additive OR NOT caller_execution STREQUAL execution_id)
                message(FATAL_ERROR "Invalid quantization caller envelope: ${row}")
            endif()
        endif()
    endif()
    if(record_type STREQUAL "IM2P_EXECUTION_TELEMETRY")
        if(NOT op STREQUAL "im2p.execute")
            message(FATAL_ERROR "Aggregate telemetry has noncanonical op: ${row}")
        endif()
        math(EXPR aggregate_count "${aggregate_count} + 1")
        string(JSON aggregate_run_id GET "${row}" run_id)
        string(JSON rtl_total GET "${row}" rtl_work_total_cycles)
        string(JSON device_backend GET "${row}" device backend)
        string(JSON device_execution GET "${row}" execution_id)
        string(JSON operation_id GET "${row}" inference_context operation_id)
        if(NOT device_backend STREQUAL "im2p_sim" OR NOT device_execution STREQUAL execution_id OR
           NOT operation_id EQUAL 1)
            message(FATAL_ERROR "Dense telemetry lost the producing operation identity")
        endif()
    elseif(record_type STREQUAL "IM2P_STRIPE_TELEMETRY")
        if(NOT op STREQUAL "im2p.execute")
            message(FATAL_ERROR "Stripe telemetry has noncanonical op: ${row}")
        endif()
        string(JSON run_id GET "${row}" run_id)
        if(target_run_id STREQUAL "")
            set(target_run_id "${run_id}")
        elseif(NOT run_id EQUAL target_run_id)
            continue()
        endif()
        string(JSON stripe_id GET "${row}" stripe_id)
        string(JSON slot GET "${row}" slot)
        string(JSON row_begin GET "${row}" row_begin)
        string(JSON row_end GET "${row}" row_end)
        string(JSON publish GET "${row}" publish_cycle)
        string(JSON completion GET "${row}" completion_cycle)
        string(JSON latency GET "${row}" latency_cycles)
        string(JSON additive GET "${row}" additive)
        math(EXPR expected_slot "${stripe_count} % 2")
        if(NOT stripe_id EQUAL stripe_count OR NOT slot EQUAL expected_slot OR
           NOT row_begin EQUAL previous_row_end OR NOT additive STREQUAL "OFF")
            message(FATAL_ERROR "Noncanonical stripe telemetry row: ${row}")
        endif()
        if(completion LESS publish)
            message(FATAL_ERROR "Real fixture unexpectedly crossed the 64-bit cycle wrap")
        endif()
        math(EXPR exact_latency "${completion} - ${publish}")
        if(NOT latency EQUAL exact_latency)
            message(FATAL_ERROR "Stripe telemetry latency does not match wrapped endpoints: ${row}")
        endif()
        set(key "${run_id}:${stripe_id}:${slot}:${row_begin}:${row_end}")
        if(key IN_LIST stripe_keys)
            message(FATAL_ERROR "Duplicate stripe telemetry key ${key}")
        endif()
        list(APPEND stripe_keys "${key}")
        set(previous_row_end "${row_end}")
        math(EXPR stripe_count "${stripe_count} + 1")
    elseif(record_type STREQUAL "QUANTIZATION_STRIPE_TELEMETRY")
        string(JSON source GET "${row}" source)
        string(JSON unit GET "${row}" unit)
        string(JSON run_id GET "${row}" run_id)
        if(target_run_id STREQUAL "")
            set(target_run_id "${run_id}")
        elseif(NOT run_id EQUAL target_run_id)
            continue()
        endif()
        string(JSON stripe_id GET "${row}" stripe_id)
        string(JSON slot GET "${row}" slot)
        string(JSON row_begin GET "${row}" row_begin)
        string(JSON row_end GET "${row}" row_end)
        string(JSON start_type TYPE "${row}" start)
        string(JSON end_type TYPE "${row}" end)
        string(JSON delta_type TYPE "${row}" delta)
        string(JSON valid GET "${row}" valid)
        string(JSON reason GET "${row}" reason)
        string(JSON start_ns GET "${row}" start_ns)
        string(JSON end_ns GET "${row}" end_ns)
        string(JSON duration_ns GET "${row}" duration_ns)
        string(JSON overlaps_type TYPE "${row}" overlaps_rtl)
        string(JSON overlaps_reason GET "${row}" overlaps_rtl_reason)
        string(JSON quant_execution GET "${row}" execution_id)
        string(JSON host_clock GET "${row}" host_clock)
        string(JSON additive GET "${row}" additive)
        math(EXPR expected_slot "${quantization_count} % 2")
        if(NOT op STREQUAL "exsia.quantize" OR
           NOT stripe_id EQUAL quantization_count OR
           NOT slot EQUAL expected_slot OR start_ns EQUAL 0 OR
           end_ns LESS start_ns OR
           NOT start_type STREQUAL "NULL" OR NOT end_type STREQUAL "NULL" OR
           NOT delta_type STREQUAL "NULL" OR NOT valid STREQUAL "OFF" OR
           NOT reason STREQUAL "structurally_cross_task" OR
           NOT overlaps_type STREQUAL "NULL" OR
           NOT overlaps_reason STREQUAL "independent_clock_domains" OR
           NOT quant_execution STREQUAL execution_id OR NOT host_clock STREQUAL "steady_clock" OR
           NOT additive STREQUAL "OFF")
            message(FATAL_ERROR "Noncanonical quantization telemetry row: ${row}")
        endif()
        math(EXPR exact_duration_ns "${end_ns} - ${start_ns}")
        if(NOT duration_ns EQUAL exact_duration_ns)
            message(FATAL_ERROR "Quantization ns duration does not match endpoints: ${row}")
        endif()
        if(row MATCHES "quantize_total|canonical.*total|cpu_work_total")
            message(FATAL_ERROR "Quantization telemetry manufactured a canonical total: ${row}")
        endif()
        list(APPEND quantization_keys
            "${run_id}:${stripe_id}:${slot}:${row_begin}:${row_end}")
        list(APPEND quantization_starts "${start_ns}")
        list(APPEND quantization_ends "${end_ns}")
        math(EXPR quantization_count "${quantization_count} + 1")
    endif()
endforeach()
if(NOT aggregate_count EQUAL 1)
    message(FATAL_ERROR "Pipeline cycle sink must contain exactly one aggregate RTL row")
endif()
if(NOT lifecycle_events STREQUAL "session_start;request_start;operation_start;operation_end;request_end;session_end")
    message(FATAL_ERROR "Incomplete pipeline request lifecycle: ${lifecycle_events}")
endif()
if(NOT npu_count EQUAL 1 OR NOT npu_cycles EQUAL rtl_total OR NOT session_finished)
    message(FATAL_ERROR "Canonical NPU sample must match the one completed dense RTL total")
endif()
if(caller_start STREQUAL "" OR caller_end STREQUAL "")
    message(FATAL_ERROR "Missing nonadditive quantization caller envelope")
endif()
if(stripe_count EQUAL 0)
    message(FATAL_ERROR "Pipeline cycle sink is missing stripe rows")
endif()
if(NOT stripe_count EQUAL expected_publications OR
   NOT quantization_count EQUAL expected_publications OR
   NOT previous_row_end EQUAL expected_rows)
    message(FATAL_ERROR
        "Stripe records do not match publication count/row partition: quantization=${quantization_count}/${expected_publications}, RTL=${stripe_count}/${expected_publications}, rows=${previous_row_end}/${expected_rows}")
endif()
if(NOT quantization_keys STREQUAL stripe_keys)
    message(FATAL_ERROR
        "Quantization and RTL stripe key sets differ: quantization=${quantization_keys}, RTL=${stripe_keys}")
endif()
foreach(key IN LISTS stripe_keys)
    if(NOT key MATCHES "^${aggregate_run_id}:")
        message(FATAL_ERROR "Stripe key ${key} does not share aggregate run ID ${aggregate_run_id}")
    endif()
endforeach()
foreach(start IN LISTS quantization_starts)
    if(start LESS caller_start)
        message(FATAL_ERROR "Stripe quantization starts before its caller envelope")
    endif()
endforeach()
foreach(end IN LISTS quantization_ends)
    if(end GREATER caller_end)
        message(FATAL_ERROR "Stripe quantization ends after its caller envelope")
    endif()
endforeach()
list(GET quantization_starts 0 first_start)
list(GET quantization_starts 1 second_start)
list(GET quantization_ends 0 first_end)
list(GET quantization_ends 1 second_end)
if(first_start GREATER second_start)
    set(intersection_start "${first_start}")
else()
    set(intersection_start "${second_start}")
endif()
if(first_end LESS second_end)
    set(intersection_end "${first_end}")
else()
    set(intersection_end "${second_end}")
endif()
set(host_overlap_ns 0)
if(intersection_end GREATER intersection_start)
    math(EXPR host_overlap_ns "${intersection_end} - ${intersection_start}")
endif()
set(detail_path "${TEST_ROOT}/output/log/exsia-cycle-detail.jsonl")
set(detail_matches 0)
set(detail_intervals 0)
if(EXISTS "${detail_path}")
    file(STRINGS "${detail_path}" detail_rows)
    foreach(row IN LISTS detail_rows)
        string(JSON run_id ERROR_VARIABLE run_error GET "${row}" run_id)
        if(run_error OR NOT run_id EQUAL aggregate_run_id)
            continue()
        endif()
        string(JSON detail_execution GET "${row}" execution_id)
        string(JSON detail_operation GET "${row}" inference_context operation_id)
        if(NOT detail_execution STREQUAL execution_id OR NOT detail_operation EQUAL 1)
            message(FATAL_ERROR "ExSIA detail lost the main log's execution/operation identity")
        endif()
        string(JSON detail_host_execution ERROR_VARIABLE host_error GET "${row}" host_timing execution_id)
        if(NOT host_error)
            if(NOT detail_host_execution STREQUAL execution_id)
                message(FATAL_ERROR "ExSIA detail host interval belongs to a different execution")
            endif()
            math(EXPR detail_intervals "${detail_intervals} + 1")
        endif()
        math(EXPR detail_matches "${detail_matches} + 1")
    endforeach()
endif()
if(TEST_REQUIRE_DETAIL AND (detail_matches EQUAL 0 OR detail_intervals LESS 2))
    message(FATAL_ERROR "This qualification requires matching ExSIA detail records")
endif()
message(STATUS "Actual RTL stripes=${stripe_count} cycles=${rtl_total}; host quantization pair intersection=${host_overlap_ns} ns; device overlap=unknown (independent clocks); detail records=${detail_matches}")
