if (NOT DEFINED TEST_SOURCE_DIR OR NOT EXISTS "${TEST_SOURCE_DIR}/CMakeLists.txt")
    message(FATAL_ERROR "TEST_SOURCE_DIR must point to the project source directory")
endif()
if (NOT DEFINED TEST_BINARY_DIR OR NOT EXISTS "${TEST_BINARY_DIR}/CMakeCache.txt")
    message(FATAL_ERROR "TEST_BINARY_DIR must point to a configured build directory")
endif()

set(production_roots
    "${TEST_SOURCE_DIR}/CMakeLists.txt"
    "${TEST_SOURCE_DIR}/build-arm64.sh"
    "${TEST_SOURCE_DIR}/build-riscv.sh"
    "${TEST_SOURCE_DIR}/build-x86.sh"
    "${TEST_SOURCE_DIR}/ggml/src/ggml-gemmini")
set(production_files)
foreach(root IN LISTS production_roots)
    if (IS_DIRECTORY "${root}")
        file(GLOB_RECURSE root_files LIST_DIRECTORIES false "${root}/*")
        list(APPEND production_files ${root_files})
    elseif (EXISTS "${root}")
        list(APPEND production_files "${root}")
    endif()
endforeach()

function(fail_match category path detail)
    file(RELATIVE_PATH relative_path "${TEST_SOURCE_DIR}" "${path}")
    message(FATAL_ERROR "${category}: ${relative_path}: ${detail}")
endfunction()

foreach(path IN LISTS production_files)
    string(TOLOWER "${path}" lower_path)
    if (lower_path MATCHES "/dec([/._-]|$)")
        fail_match("historical DEC file" "${path}" "path contains a DEC component")
    endif()

    file(READ "${path}" content)
    string(TOLOWER "${content}" lower_content)

    if (content MATCHES "GGML_GEMMINI_DEC|DEC_THREADS|DEC_GROUP|DEC_VALIDATION|ActivationDEC|quants::dec|[A-Za-z0-9_]dec_|dec_[A-Za-z0-9_]")
        fail_match("historical DEC identifier/option/runtime token" "${path}" "matched the DEC deny-list")
    endif()
    if (content MATCHES "[\"']DEC[\"']")
        fail_match("historical DEC runtime token" "${path}" "contains the DEC selector token")
    endif()
    if (lower_content MATCHES "rmd_backend[^\n]*(inherit|auto|fallback)|(inherit|auto|fallback)[^\n]*rmd_backend")
        fail_match("forbidden RMD backend semantics" "${path}" "RMD backend uses INHERIT/AUTO/fallback semantics")
    endif()
    if (lower_content MATCHES "(cpu_compact|compact_cpu|cpu[^\n]*compact[^\n]*(call|execute)|compact[^\n]*(call|execute)[^\n]*cpu)")
        fail_match("compact CPU production token/call" "${path}" "matched the compact CPU deny-list")
    endif()
endforeach()

set(executor "${TEST_SOURCE_DIR}/ggml/src/ggml-gemmini/residual/rmd/rmd-executor.cpp")
file(STRINGS "${executor}" executor_lines)
set(test_guard_depth 0)
set(preprocessor_depth 0)
set(scalar_occurrences 0)
foreach(line IN LISTS executor_lines)
    if (line MATCHES "^[ \t]*#[ \t]*(if|ifdef|ifndef)")
        math(EXPR preprocessor_depth "${preprocessor_depth} + 1")
        if (line MATCHES "GGML_GEMMINI_TESTING" AND test_guard_depth EQUAL 0)
            set(test_guard_depth "${preprocessor_depth}")
        endif()
    endif()
    if (line MATCHES "scalar_reference")
        math(EXPR scalar_occurrences "${scalar_occurrences} + 1")
        if (test_guard_depth EQUAL 0)
            fail_match("unguarded scalar compact symbol" "${executor}" "${line}")
        endif()
    endif()
    if (line MATCHES "^[ \t]*#[ \t]*endif")
        if (test_guard_depth EQUAL preprocessor_depth)
            set(test_guard_depth 0)
        endif()
        math(EXPR preprocessor_depth "${preprocessor_depth} - 1")
    endif()
endforeach()
if (NOT scalar_occurrences EQUAL 2)
    message(FATAL_ERROR "Expected exactly two test-guarded scalar compact symbols, found ${scalar_occurrences}")
endif()

set(selector_files
    "${TEST_SOURCE_DIR}/ggml/src/ggml-gemmini/ggml-gemmini-matmul.cpp")
file(GLOB_RECURSE residual_files LIST_DIRECTORIES false
    "${TEST_SOURCE_DIR}/ggml/src/ggml-gemmini/residual/*")
list(APPEND selector_files ${residual_files})
foreach(path IN LISTS selector_files)
    file(READ "${path}" content)
    if (content MATCHES "args[.]tiled_matmul_type[ \t\r\n]*=")
        fail_match("residual selector mutation" "${path}" "assigns args.tiled_matmul_type")
    endif()
endforeach()

file(READ "${TEST_BINARY_DIR}/CMakeCache.txt" cache)
foreach(needle IN ITEMS GGML_GEMMINI_DEC DEC_THREADS DEC_GROUP DEC_VALIDATION)
    string(FIND "${cache}" "${needle}" found_at)
    if (NOT found_at EQUAL -1)
        message(FATAL_ERROR "historical DEC build option in CMakeCache.txt: ${needle}")
    endif()
endforeach()
foreach(needle IN ITEMS
        "GGML_GEMMINI_DEFAULT_RMD_BACKEND:STRING=INHERIT"
        "GGML_GEMMINI_DEFAULT_RMD_BACKEND:STRING=AUTO"
        "GGML_GEMMINI_DEFAULT_RMD_BACKEND:STRING=FALLBACK")
    string(FIND "${cache}" "${needle}" found_at)
    if (NOT found_at EQUAL -1)
        message(FATAL_ERROR "forbidden RMD backend build semantic in CMakeCache.txt: ${needle}")
    endif()
endforeach()

message(STATUS "Gemmini RMD backend source/build deny-list passed")
