if(NOT EXISTS "${TEST_MANIFEST}" OR NOT EXISTS "${TEST_HEADER}")
    message(FATAL_ERROR "numerical memory contract inputs missing")
endif()
file(READ "${TEST_MANIFEST}" manifest)
string(JSON contract GET "${manifest}" build_config hardware_lowering_contract)
file(READ "${TEST_HEADER}" header)
foreach(pair IN ITEMS "BANK_NUM=bank_count" "BANK_ROWS=bank_rows" "ACC_ROWS=accumulator_rows")
    string(REPLACE "=" ";" names "${pair}")
    list(GET names 0 macro)
    list(GET names 1 field)
    string(JSON expected GET "${contract}" facts memory "${field}")
    string(REGEX MATCH "#define[ \t]+${macro}[ \t]+([0-9]+)" definition "${header}")
    if(NOT definition OR NOT CMAKE_MATCH_1 STREQUAL expected)
        message(FATAL_ERROR "${macro} generated=${CMAKE_MATCH_1} selected-hardware=${expected}")
    endif()
endforeach()
