if(NOT DEFINED MATMUL_SOURCE)
    message(FATAL_ERROR "MATMUL_SOURCE is required")
endif()
file(READ "${MATMUL_SOURCE}" source)

function(extract_between output begin_marker end_marker)
    string(FIND "${source}" "${begin_marker}" begin)
    string(FIND "${source}" "${end_marker}" end)
    if(begin EQUAL -1 OR end EQUAL -1 OR end LESS_EQUAL begin)
        message(FATAL_ERROR "cannot extract ${begin_marker}")
    endif()
    math(EXPR length "${end} - ${begin}")
    string(SUBSTRING "${source}" ${begin} ${length} value)
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(require_count value needle expected label)
    set(rest "${value}")
    set(count 0)
    while(TRUE)
        string(FIND "${rest}" "${needle}" position)
        if(position EQUAL -1)
            break()
        endif()
        string(LENGTH "${needle}" needle_length)
        math(EXPR next "${position} + ${needle_length}")
        string(SUBSTRING "${rest}" ${next} -1 rest)
        math(EXPR count "${count} + 1")
    endwhile()
    if(NOT count EQUAL expected)
        message(FATAL_ERROR "${label}: expected ${expected}, found ${count}")
    endif()
endfunction()

function(require_token value token label)
    string(FIND "${value}" "${token}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "${label}: missing ${token}")
    endif()
endfunction()

function(require_absent value token label)
    string(FIND "${value}" "${token}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "${label}: unexpected ${token}")
    endif()
endfunction()

extract_between(routes "#if CYCLE_DETAIL && defined(__linux__) && defined(__aarch64__)\nnamespace {" "namespace test_detail")
extract_between(dense "MatmulStatus execute_dense_stripe" "MatmulStatus accept_external_dense_completion")
extract_between(external "MatmulStatus accept_external_dense_completion" "MatmulStatus execute_rmd_stripe")
extract_between(rmd "MatmulStatus execute_rmd_stripe" "MatmulStatus compose_rmd_stripe")
extract_between(compose "MatmulStatus compose_rmd_stripe" "MatmulStatus finalize_stripe")
extract_between(finalize "MatmulStatus finalize_stripe" "MatmulStatus finish_execution")

require_count("${dense}" "cycle::read_sample()" 2 "Dense exact pair")
require_count("${external}" "cycle::read_sample()" 1 "external Dense marker")
require_count("${rmd}" "cycle::read_sample()" 3 "shared residual/backend boundaries")
require_count("${compose}" "cycle::read_sample()" 2 "packet Compose pair")
require_count("${finalize}" "cycle::read_sample()" 5 "Finalize/Merge/residual boundaries")

require_token("${external}" "telemetry_dense_marker_only = true" "external marker classification")
require_token("${rmd}" "telemetry_residual_sampled = true" "residual boundary presence")
require_token("${rmd}" "telemetry_residual_start_sample = residual_start_sample" "residual sample reuse")
require_token("${rmd}" "telemetry_backend_start_sample = backend_start_sample" "backend start reuse")
require_token("${rmd}" "telemetry_backend_end_sample = backend_end_sample" "backend end reuse")
require_token("${compose}" "job.direct_residual_ != nullptr || packet == nullptr" "direct Compose exclusion")
require_token("${compose}" "std::lock_guard<std::mutex> lock(*job.job_mutex_);\n#if CYCLE_DETAIL && defined(__linux__) && defined(__aarch64__)\n        job.metrics_.telemetry_compose_start_sample = cycle::read_sample();\n#endif\n        job.metrics_.compose_start_ns = now_ns();" "Compose PMU start owns locked ns range")
require_token("${compose}" "job.metrics_.compose_end_ns = now_ns();\n#if CYCLE_DETAIL && defined(__linux__) && defined(__aarch64__)\n        job.metrics_.telemetry_compose_end_sample = cycle::read_sample();" "Compose PMU end is adjacent to ns end")
require_token("${finalize}" "telemetry_residual_end_sample =\n                job.metrics_.telemetry_merge_end_sample" "Merge/residual end reuse")
require_token("${finalize}" "job.metrics_.cpu_work.merge.additive = false" "Merge non-additive")
require_token("${finalize}" "job.metrics_.telemetry_finalize_start_sample,\n            job.metrics_.telemetry_finalize_end_sample" "Finalize owns its exact endpoints")
require_token("${finalize}" "job.metrics_.cpu_work.finalize.cycles.reset();\n            job.metrics_.cpu_work.finalize.coverage = CpuWorkCoverage::invalid;\n            job.metrics_.cpu_work.finalize.additive = false;\n            job.metrics_.cpu_work.finalize.reason = \"failed_operation\";" "failed Merge invalidates Finalize atomically")
require_absent("${source}" "select_rmd_post_cpu_work" "dead post-selection seam")

foreach(format IN ITEMS q4_h1 q4_hp1 q8_h1 q8_hp1 q16_h1 q16_hp1)
    require_count("${routes}" "case Format::${format}:" 1 "checked-software ${format} route")
endforeach()
require_token("${rmd}" "direct != nullptr ? RmdCpuRoute::cpu_direct" "direct leaf route")
require_token("${rmd}" "direct_cpu_work(direct_metrics), backend" "Task 5 leaf consumption")
require_token("${source}" "return RmdCpuRoute::native_accelerator" "native unavailable route")
require_count("${source}" "cycle::read_sample()" 13 "Task 7 static Jetson sample sites")
require_count("${dense}" "#elif CYCLE_DETAIL" 1 "Dense non-Jetson branch")
require_count("${rmd}" "#elif LOG_CYCLE" 3 "RMD non-Jetson branches")
require_count("${compose}" "#if CYCLE_DETAIL && defined(__linux__) && defined(__aarch64__)" 2 "Compose Jetson guards")
require_count("${finalize}" "#if CYCLE_DETAIL && defined(__linux__) && defined(__aarch64__)" 5 "Finalize Jetson guards")
