if(NOT DEFINED TEST_SOURCE_DIR OR NOT IS_DIRECTORY "${TEST_SOURCE_DIR}")
    message(FATAL_ERROR "TEST_SOURCE_DIR must be an existing source directory")
endif()

set(forbidden_symbols
    "GGML_GEMMINI_DEFAULT_" "STRIPE_ROWS"
    "GEMMINI_" "STRIPE_ROWS")
list(GET forbidden_symbols 0 build_prefix)
list(GET forbidden_symbols 1 stripe_suffix)
list(GET forbidden_symbols 2 runtime_prefix)
list(GET forbidden_symbols 3 runtime_suffix)
set(legacy_build_symbol "${build_prefix}${stripe_suffix}")
set(legacy_runtime_symbol "${runtime_prefix}${runtime_suffix}")

get_filename_component(source_root "${TEST_SOURCE_DIR}" REALPATH)
set(source_roots .github ci cmake common evaluation examples ggml gguf-py grammars include pocs scripts src tests tools)
set(source_extensions "c|cc|cpp|cxx|h|hh|hpp|hxx|inc|ipp|tpp|ixx|s|asm|cu|cuh|m|mm|metal|cl|comp|swift|kt|kts|py|sh|bash|zsh|ps1|bat|cmd|cmake|mk|toml|js|mjs|cjs|jsx|ts|tsx|rs|go|in")
set(text_extensions "json|jsonc|yaml|yml|txt|md|xml|properties|pro|css|html|gbnf|vim|csv|sql|pbxproj")
set(directories "${source_root}")
set(repository_files)
while(directories)
    list(GET directories 0 directory)
    list(REMOVE_AT directories 0)
    file(GLOB entries LIST_DIRECTORIES true "${directory}/*")
    foreach(path IN LISTS entries)
        get_filename_component(name "${path}" NAME)
        if(IS_SYMLINK "${path}")
            continue()
        endif()
        if(IS_DIRECTORY "${path}")
            if(name MATCHES "^(build.*|\\.git|\\.omo|\\.omx|\\.cache|\\.ruff_cache|\\.pytest_cache|\\.venv|\\.senpi|\\.codegraph|Testing|CMakeFiles|generated|target|dist|coverage|node_modules|__pycache__|models?|logs?|runs?|results?|output|cache|graphify-out)$")
                continue()
            endif()
            if(directory STREQUAL source_root)
                list(FIND source_roots "${name}" root_index)
                if(root_index EQUAL -1)
                    continue()
                endif()
            endif()
            list(APPEND directories "${path}")
        else()
            string(TOLOWER "${name}" lower_name)
            if(lower_name MATCHES "\\.(${source_extensions})$" OR
               lower_name MATCHES "^(cmakelists\\.txt|makefile|dockerfile.*|cmake(user)?presets\\.json|package(-lock)?\\.json)$" OR
               (NOT directory STREQUAL source_root AND lower_name MATCHES "\\.(${text_extensions})$"))
                list(APPEND repository_files "${path}")
            endif()
        endif()
    endforeach()
endwhile()

set(matches "")
set(inspected_files)
foreach(path IN LISTS repository_files)
    file(RELATIVE_PATH relative_path "${source_root}" "${path}")
    if(relative_path STREQUAL "tests/parse-stripe-ws-profile.py")
        continue()
    endif()
    list(APPEND inspected_files "${relative_path}")
    file(READ "${path}" content)
    foreach(symbol IN ITEMS "${legacy_build_symbol}" "${legacy_runtime_symbol}")
        string(FIND "${content}" "${symbol}" found_at)
        if(NOT found_at EQUAL -1)
            list(APPEND matches "${relative_path}: ${symbol}")
        endif()
    endforeach()
endforeach()

if(NOT inspected_files)
    message(FATAL_ERROR "No maintained source files found in TEST_SOURCE_DIR")
endif()
if(DEFINED TEST_INVENTORY)
    list(JOIN inspected_files "\n" inventory)
    file(WRITE "${TEST_INVENTORY}" "${inventory}\n")
endif()
list(LENGTH inspected_files source_count)
message(STATUS "Geometry contract inspected ${source_count} maintained source files")

if(matches)
    list(JOIN matches "\n  " formatted_matches)
    message(FATAL_ERROR "Obsolete Gemmini stripe-row symbols remain:\n  ${formatted_matches}")
endif()
