if(NOT DEFINED TEST_BINARY OR NOT DEFINED TEST_ROOT OR NOT DEFINED TEST_DIM)
    message(FATAL_ERROR "TEST_BINARY, TEST_ROOT, and TEST_DIM are required")
endif()
math(EXPR expected_publications "2")
math(EXPR expected_rows "16 * ${TEST_DIM}")

file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}")

execute_process(
    COMMAND "${TEST_BINARY}" --case pipeline
    WORKING_DIRECTORY "${TEST_ROOT}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR
        "Pipeline cycle fixture failed (${result})\nstdout:\n${output}\nstderr:\n${error}")
endif()

set(cycle_path "${TEST_ROOT}/output/log/cycle-log.jsonl")
if(NOT EXISTS "${cycle_path}")
    message(FATAL_ERROR "Pipeline cycle fixture did not create ${cycle_path}")
endif()
file(READ "${cycle_path}" cycle_log)

string(FIND "${cycle_log}"
    "\"op\":\"gemmini.quantize_activation\"" cpu_quant_at)
if(NOT cpu_quant_at EQUAL -1)
    message(FATAL_ERROR
        "Pipeline cycle sink contains overlapping CPU activation quantization")
endif()

string(REPLACE "\n" ";" cycle_rows "${cycle_log}")
set(aggregate_count 0)
set(stripe_count 0)
set(quantization_count 0)
set(aggregate_run_id "")
set(target_run_id "")
set(previous_row_end 0)
set(stripe_keys "")
set(quantization_keys "")
foreach(row IN LISTS cycle_rows)
    if(row STREQUAL "")
        continue()
    endif()
    string(JSON record_type ERROR_VARIABLE json_error GET "${row}" record_type)
    if(json_error)
        message(FATAL_ERROR "Pipeline cycle sink contains malformed JSON: ${row}")
    endif()
    string(JSON version GET "${row}" version)
    string(JSON op GET "${row}" op)
    if(NOT version EQUAL 2)
        message(FATAL_ERROR "Pipeline cycle sink contains non-v2 row: ${row}")
    endif()
    if(record_type STREQUAL "IM2P_EXECUTION_TELEMETRY")
        if(NOT op STREQUAL "im2p.execute")
            message(FATAL_ERROR "Aggregate telemetry has noncanonical op: ${row}")
        endif()
        math(EXPR aggregate_count "${aggregate_count} + 1")
        string(JSON aggregate_run_id GET "${row}" run_id)
        string(JSON rtl_total GET "${row}" rtl_work_total_cycles)
    elseif(record_type STREQUAL "IM2P_STRIPE_TELEMETRY")
        if(NOT op STREQUAL "im2p.execute")
            message(FATAL_ERROR "Stripe telemetry has noncanonical op: ${row}")
        endif()
        string(JSON run_id GET "${row}" run_id)
        if(target_run_id STREQUAL "")
            set(target_run_id "${run_id}")
        elseif(NOT run_id EQUAL target_run_id)
            continue()
        endif()
        string(JSON stripe_id GET "${row}" stripe_id)
        string(JSON slot GET "${row}" slot)
        string(JSON row_begin GET "${row}" row_begin)
        string(JSON row_end GET "${row}" row_end)
        string(JSON publish GET "${row}" publish_cycle)
        string(JSON completion GET "${row}" completion_cycle)
        string(JSON latency GET "${row}" latency_cycles)
        string(JSON additive GET "${row}" additive)
        math(EXPR expected_slot "${stripe_count} % 2")
        if(NOT stripe_id EQUAL stripe_count OR NOT slot EQUAL expected_slot OR
           NOT row_begin EQUAL previous_row_end OR NOT additive STREQUAL "OFF")
            message(FATAL_ERROR "Noncanonical stripe telemetry row: ${row}")
        endif()
        if(completion LESS publish)
            message(FATAL_ERROR "Real fixture unexpectedly crossed the 64-bit cycle wrap")
        endif()
        math(EXPR exact_latency "${completion} - ${publish}")
        if(NOT latency EQUAL exact_latency)
            message(FATAL_ERROR "Stripe telemetry latency does not match wrapped endpoints: ${row}")
        endif()
        set(key "${run_id}:${stripe_id}:${slot}:${row_begin}:${row_end}")
        if(key IN_LIST stripe_keys)
            message(FATAL_ERROR "Duplicate stripe telemetry key ${key}")
        endif()
        list(APPEND stripe_keys "${key}")
        set(previous_row_end "${row_end}")
        math(EXPR stripe_count "${stripe_count} + 1")
    elseif(record_type STREQUAL "QUANTIZATION_STRIPE_TELEMETRY")
        string(JSON source GET "${row}" source)
        string(JSON unit GET "${row}" unit)
        string(JSON run_id GET "${row}" run_id)
        if(target_run_id STREQUAL "")
            set(target_run_id "${run_id}")
        elseif(NOT run_id EQUAL target_run_id)
            continue()
        endif()
        string(JSON stripe_id GET "${row}" stripe_id)
        string(JSON slot GET "${row}" slot)
        string(JSON row_begin GET "${row}" row_begin)
        string(JSON row_end GET "${row}" row_end)
        string(JSON start_type TYPE "${row}" start)
        string(JSON end_type TYPE "${row}" end)
        string(JSON delta_type TYPE "${row}" delta)
        string(JSON valid GET "${row}" valid)
        string(JSON reason GET "${row}" reason)
        string(JSON start_ns GET "${row}" start_ns)
        string(JSON end_ns GET "${row}" end_ns)
        string(JSON duration_ns GET "${row}" duration_ns)
        string(JSON overlaps_rtl GET "${row}" overlaps_rtl)
        string(JSON additive GET "${row}" additive)
        math(EXPR expected_slot "${quantization_count} % 2")
        if(NOT op STREQUAL "exsia.quantize" OR
           NOT stripe_id EQUAL quantization_count OR
           NOT slot EQUAL expected_slot OR start_ns EQUAL 0 OR
           end_ns LESS start_ns OR
           NOT start_type STREQUAL "NULL" OR NOT end_type STREQUAL "NULL" OR
           NOT delta_type STREQUAL "NULL" OR NOT valid STREQUAL "OFF" OR
           NOT reason STREQUAL "structurally_cross_task" OR
           NOT overlaps_rtl STREQUAL "ON" OR NOT additive STREQUAL "OFF")
            message(FATAL_ERROR "Noncanonical quantization telemetry row: ${row}")
        endif()
        math(EXPR exact_duration_ns "${end_ns} - ${start_ns}")
        if(NOT duration_ns EQUAL exact_duration_ns)
            message(FATAL_ERROR "Quantization ns duration does not match endpoints: ${row}")
        endif()
        if(row MATCHES "quantize_total|canonical.*total|cpu_work_total")
            message(FATAL_ERROR "Quantization telemetry manufactured a canonical total: ${row}")
        endif()
        list(APPEND quantization_keys
            "${run_id}:${stripe_id}:${slot}:${row_begin}:${row_end}")
        math(EXPR quantization_count "${quantization_count} + 1")
    endif()
endforeach()
if(NOT aggregate_count EQUAL 1)
    message(FATAL_ERROR "Pipeline cycle sink must contain exactly one aggregate RTL row")
endif()
if(stripe_count EQUAL 0)
    message(FATAL_ERROR "Pipeline cycle sink is missing stripe rows")
endif()
if(NOT stripe_count EQUAL expected_publications OR
   NOT quantization_count EQUAL expected_publications OR
   NOT previous_row_end EQUAL expected_rows)
    message(FATAL_ERROR
        "Stripe records do not match publication count/row partition: quantization=${quantization_count}/${expected_publications}, RTL=${stripe_count}/${expected_publications}, rows=${previous_row_end}/${expected_rows}")
endif()
if(NOT quantization_keys STREQUAL stripe_keys)
    message(FATAL_ERROR
        "Quantization and RTL stripe key sets differ: quantization=${quantization_keys}, RTL=${stripe_keys}")
endif()
foreach(key IN LISTS stripe_keys)
    if(NOT key MATCHES "^${aggregate_run_id}:")
        message(FATAL_ERROR "Stripe key ${key} does not share aggregate run ID ${aggregate_run_id}")
    endif()
endforeach()
