string(RANDOM LENGTH 16 run_suffix)
set(log_dir "${TEST_OUTPUT_DIR}/cycle-sim-${TEST_MODE}-${run_suffix}")
file(MAKE_DIRECTORY "${log_dir}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env "GEMMINI_LOG_DIR=${log_dir}"
    "${TEST_EXECUTABLE}" "${TEST_MODE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
message(STATUS "NPU trace fixture: ${log_dir}/npu-cycle-trace.jsonl")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "${output}\n${error}")
endif()
set(cycle_log "${log_dir}/cycle-log.jsonl")
set(npu_trace "${log_dir}/npu-cycle-trace.jsonl")
if(EXISTS "${cycle_log}")
    file(READ "${cycle_log}" cycle_records)
    if(cycle_records MATCHES "\"record_type\":\"NPU_OPERATOR_SEGMENT\"")
        message(FATAL_ERROR "CPU-functional collection emitted legacy online NPU timing")
    endif()
    file(STRINGS "${cycle_log}" potal_records REGEX "\"duration_role\":\"POTAL_HOST\"")
    foreach(record IN LISTS potal_records)
        if(NOT record MATCHES "\"interval_class\":\"CANONICAL_ADDITIVE\"")
            message(FATAL_ERROR "PoTal host duration lacks canonical additive classification")
        endif()
    endforeach()
    if(EXISTS "${npu_trace}")
        file(READ "${npu_trace}" npu_records)
        if(npu_records MATCHES "\"stage_name\":\"im2p.output_reconstruction\"" AND
           NOT cycle_records MATCHES "\"op\":\"im2p.output_reconstruction\"[^\n]*\"interval_class\":\"CANONICAL_ADDITIVE\"[^\n]*\"duration_role\":\"POTAL_HOST\"")
            message(FATAL_ERROR "output reconstruction host stage lacks canonical measured cost")
        endif()
    endif()
endif()
execute_process(COMMAND "${TEST_PYTHON}"
    "${CMAKE_CURRENT_LIST_DIR}/check-cycle-sim-host-stages.py" "${npu_trace}" "${cycle_log}"
    RESULT_VARIABLE host_result OUTPUT_VARIABLE host_output ERROR_VARIABLE host_error)
if(NOT host_result EQUAL 0)
    message(FATAL_ERROR "${host_output}\n${host_error}")
endif()
