#pragma once

// Value-free production dispatch provenance, deliberately separate from cycle
// telemetry. The writer owns its file and fails closed on any I/O/integrity
// error. An empty path creates no session and changes no execution semantics.
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>

namespace ggml::gemmini::optrace {

struct RunInfo {
    std::string run_id = "run-0";
    std::string model;
    std::string profile;
    uint32_t activation_bits = 0, weight_bits = 0, dim = 0;
    std::string backend;
    std::string mode;
    bool residual_enabled = false;
    uint64_t prompt_tokens = 0, requested_generated_tokens = 0;
    std::map<std::string, std::string> source_commits;
    std::map<std::string, std::string> source_worktree_sha256;
    std::string hardware_contract_sha256;
    std::string runtime_manifest_sha256;
};

// Build identities are generated by CMake, not supplied as measured answers.
RunInfo compiled_run_info(const std::string &model, uint64_t prompt_tokens,
                          uint64_t requested_generated_tokens);

struct Work {
    std::string layer;
    std::string operation = "gemmini.matmul";
    std::string provenance = "dense_main";
    std::string scope = "full";
    uint32_t activation_bits = 0, weight_bits = 0, dim = 0;
    uint64_t m = 0, n = 0, k = 0;
    uint64_t tile_i_count = 0, tile_j_count = 0, tile_k_count = 0;
    // For stripe work, geometry_m is the parent geometry's M, while m is
    // exactly the accepted stripe's rows. No tile selection occurs here.
    uint64_t geometry_m = 0, row_begin = 0, row_count = 0;
    std::optional<uint64_t> stripe_id, host_slot, original_block_id;
    uint64_t activation_stride_bytes = 0, weight_stride_bytes = 0;
    uint64_t output_stride_bytes = 0, scale_stride_elements = 0;
    uint32_t block_size = 32, vector_op = 5, output_domain = 2;
    uint32_t production_geometry_version = 1;
    uint64_t work_context = 0;
    // Residual compact rows may stack radix lanes. Preserve the host stripe
    // separately rather than pretending its row range equals compact M.
    uint64_t source_row_begin = 0, source_row_count = 0;
    uint64_t column_begin = 0, group_index = 0;
    bool rmd_raw = false, host_integer_block_multiply = false;
};

class Session;
struct Context {
    std::shared_ptr<Session> session;
    uint64_t phase_id = 0;
    std::optional<uint64_t> parent_invocation_id;
    explicit operator bool() const noexcept { return bool(session); }
};

// Driver-local, never a process-global current phase. Asynchronous owners
// explicitly copy this context before starting a worker and bind that copy.
Context current_context();
class ScopedContext {
public:
    explicit ScopedContext(Context context);
    ~ScopedContext() noexcept;
    ScopedContext(const ScopedContext &) = delete;
    ScopedContext &operator=(const ScopedContext &) = delete;
private:
    Context previous_;
};

class Session : public std::enable_shared_from_this<Session> {
public:
    static std::shared_ptr<Session> start(const char *path, const RunInfo &info);
    ~Session() noexcept;
    Context phase(const std::string &kind, std::optional<uint64_t> decode_index,
                  uint64_t input_tokens);
    Context parent_begin(const Context &phase, const Work &descriptor);
    void parent_end(const Context &parent);
    void accepted(const Context &context, const Work &work);
    // Call only with independently produced execution counters, never with
    // a count derived from accepted(), serialization, or the trace file.
    void independent_count(const Context &context, const std::string &layer,
                           const std::string &provenance, uint64_t count);
    void finish(bool success = true, const std::string &reason = "");
    Session(const Session &) = delete;
    Session &operator=(const Session &) = delete;
private:
    struct Impl;
    explicit Session(std::unique_ptr<Impl> impl);
    std::unique_ptr<Impl> impl_;
};

} // namespace ggml::gemmini::optrace
