# Gemmini compile-time switches (source of truth: root cache + build scripts).
foreach(_metric IN ITEMS ACT ACT_QUANT RESIDUAL SCALE)
    set(GGML_GEMMINI_${_metric}_METRICS "0" CACHE STRING "Enable independent ${_metric} evaluation metrics (0|1)")
    set_property(CACHE GGML_GEMMINI_${_metric}_METRICS PROPERTY STRINGS 0 1)
    if(NOT GGML_GEMMINI_${_metric}_METRICS MATCHES "^[01]$")
        message(FATAL_ERROR "GGML_GEMMINI_${_metric}_METRICS must be 0 or 1")
    endif()
    foreach(_flags IN ITEMS CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
            CMAKE_CXX_FLAGS_RELWITHDEBINFO CMAKE_CXX_FLAGS_MINSIZEREL)
        if("${${_flags}}" MATCHES "(^|[ \t])[-/]DGGML_GEMMINI_${_metric}_METRICS([= \t]|$)")
            message(FATAL_ERROR "Use GGML_GEMMINI_${_metric}_METRICS cache option, not ${_flags}")
        endif()
    endforeach()
endforeach()
if(GGML_GEMMINI_ACT_METRICS)
    set(GGML_GEMMINI_ACT_QUANT_METRICS 1)
endif()
set(CYCLE_SIM "0" CACHE STRING "Enable PoTal cycle-simulation trace collection (0|1)")
set_property(CACHE CYCLE_SIM PROPERTY STRINGS 0 1)
if(NOT CYCLE_SIM MATCHES "^[01]$")
    message(FATAL_ERROR "CYCLE_SIM must be 0 or 1, got '${CYCLE_SIM}'")
endif()
set(GGML_GEMMINI_PRINT_TILE "0" CACHE STRING "Gemmini PRINT_TILE macro (0|1)")
set_property(CACHE GGML_GEMMINI_PRINT_TILE PROPERTY STRINGS 0 1)
set(GGML_GEMMINI_OPTION "CPU" CACHE STRING "Gemmini OPTION macro (CPU|OS|WS)")
set_property(CACHE GGML_GEMMINI_OPTION PROPERTY STRINGS CPU OS WS)
string(TOUPPER "${GGML_GEMMINI_OPTION}" _GGML_GEMMINI_OPTION_UPPER)
set(_GGML_GEMMINI_OPTION_VALUES CPU OS WS)
list(FIND _GGML_GEMMINI_OPTION_VALUES "${_GGML_GEMMINI_OPTION_UPPER}" _GGML_GEMMINI_OPTION_INDEX)
if(_GGML_GEMMINI_OPTION_INDEX EQUAL -1)
    message(FATAL_ERROR
        "GGML_GEMMINI_OPTION must be one of CPU|OS|WS, got '${GGML_GEMMINI_OPTION}'")
endif()
set(GGML_GEMMINI_OPTION "${_GGML_GEMMINI_OPTION_UPPER}" CACHE STRING
    "Gemmini OPTION macro (CPU|OS|WS)" FORCE)
set_property(CACHE GGML_GEMMINI_OPTION PROPERTY STRINGS CPU OS WS)
set(GGML_GEMMINI_FULL_C "1" CACHE STRING "Gemmini FULL_C macro (0|1)")
set_property(CACHE GGML_GEMMINI_FULL_C PROPERTY STRINGS 0 1)
set(GGML_GEMMINI_LOW_D "0" CACHE STRING "Gemmini LOW_D macro (0|1)")
set_property(CACHE GGML_GEMMINI_LOW_D PROPERTY STRINGS 0 1)
set(GGML_GEMMINI_TRANSPOSE_B "1" CACHE STRING "Gemmini TRANSPOSE_B macro (0|1)")
set_property(CACHE GGML_GEMMINI_TRANSPOSE_B PROPERTY STRINGS 0 1)
set(GGML_GEMMINI_WS_DEBUG "0" CACHE STRING "Gemmini WS debug logs (0|1)")
set_property(CACHE GGML_GEMMINI_WS_DEBUG PROPERTY STRINGS 0 1)
set(GGML_GEMMINI_WS_LOOP_CYCLE "0" CACHE STRING "Gemmini WS loop hardware cycle profiling (0|1)")
set_property(CACHE GGML_GEMMINI_WS_LOOP_CYCLE PROPERTY STRINGS 0 1)
set(GGML_GEMMINI_DISABLE_WS_REUSE "0" CACHE STRING "Disable WS A/B reuse for debugging (0|1)")
set_property(CACHE GGML_GEMMINI_DISABLE_WS_REUSE PROPERTY STRINGS 0 1)

# ---------------------------------------------------------------------------
# Adding a new compile-time option
# ---------------------------------------------------------------------------
# 1. Choose a macro name (must match the C++ header, e.g. GGML_GEMMINI_*).
# 2. Add a set(CACHE ...) + set_property(STRINGS ...) block below.
# 3. Validate the string input and map it to an integer value.
# 4. Append the integer to GGML_GEMMINI_COMPILE_DEFS so it reaches #ifdef.
# 5. In the C++ header add the enum entry, #elif branch, and static_assert.
# 6. In the dispatch site (e.g. quantize.cpp) add a case / if constexpr branch.
# ---------------------------------------------------------------------------
set(GGML_GEMMINI_COMPUTE_TYPE "INT" CACHE STRING "Gemmini compute type: INT or FLOAT")
set_property(CACHE GGML_GEMMINI_COMPUTE_TYPE PROPERTY STRINGS INT FLOAT)
string(TOUPPER "${GGML_GEMMINI_COMPUTE_TYPE}" _GGML_GEMMINI_COMPUTE_TYPE_UPPER)
if(NOT _GGML_GEMMINI_COMPUTE_TYPE_UPPER STREQUAL "INT" AND
   NOT _GGML_GEMMINI_COMPUTE_TYPE_UPPER STREQUAL "FLOAT")
    message(FATAL_ERROR "GGML_GEMMINI_COMPUTE_TYPE must be one of: INT, FLOAT")
endif()
if(_GGML_GEMMINI_COMPUTE_TYPE_UPPER STREQUAL "INT")
    set(_GGML_GEMMINI_COMPUTE_TYPE_VALUE 0)
else()
    set(_GGML_GEMMINI_COMPUTE_TYPE_VALUE 1)
endif()

set(GGML_GEMMINI_DEQUANT_FP_TEST OFF CACHE BOOL "Validate FLOAT with quantized/dequantized activations")
if(GGML_GEMMINI_DEQUANT_FP_TEST AND NOT _GGML_GEMMINI_COMPUTE_TYPE_UPPER STREQUAL "FLOAT")
    message(FATAL_ERROR "GGML_GEMMINI_DEQUANT_FP_TEST requires GGML_GEMMINI_COMPUTE_TYPE=FLOAT")
endif()
if(GGML_GEMMINI_DEQUANT_FP_TEST)
    set(_GGML_GEMMINI_DEQUANT_FP_TEST_VALUE 1)
else()
    set(_GGML_GEMMINI_DEQUANT_FP_TEST_VALUE 0)
endif()

set(GGML_GEMMINI_ACTIVATION_QUANT "EXSIA" CACHE STRING "Gemmini activation quant type")
set_property(CACHE GGML_GEMMINI_ACTIVATION_QUANT PROPERTY STRINGS EXSIA TENSOR TOKEN BLOCK STRIPE)
string(TOUPPER "${GGML_GEMMINI_ACTIVATION_QUANT}" _GGML_GEMMINI_ACTIVATION_QUANT_UPPER)
if(NOT _GGML_GEMMINI_ACTIVATION_QUANT_UPPER STREQUAL "EXSIA" AND
   NOT _GGML_GEMMINI_ACTIVATION_QUANT_UPPER STREQUAL "TENSOR" AND
   NOT _GGML_GEMMINI_ACTIVATION_QUANT_UPPER STREQUAL "TOKEN" AND
   NOT _GGML_GEMMINI_ACTIVATION_QUANT_UPPER STREQUAL "BLOCK" AND
   NOT _GGML_GEMMINI_ACTIVATION_QUANT_UPPER STREQUAL "STRIPE")
    message(FATAL_ERROR "GGML_GEMMINI_ACTIVATION_QUANT must be EXSIA, TENSOR, TOKEN, BLOCK, or STRIPE, got '${GGML_GEMMINI_ACTIVATION_QUANT}'")
endif()
if(_GGML_GEMMINI_ACTIVATION_QUANT_UPPER STREQUAL "EXSIA")
    set(_GGML_GEMMINI_ACTIVATION_QUANT_VALUE 0)
elseif(_GGML_GEMMINI_ACTIVATION_QUANT_UPPER STREQUAL "TENSOR")
    set(_GGML_GEMMINI_ACTIVATION_QUANT_VALUE 1)
elseif(_GGML_GEMMINI_ACTIVATION_QUANT_UPPER STREQUAL "TOKEN")
    set(_GGML_GEMMINI_ACTIVATION_QUANT_VALUE 2)
elseif(_GGML_GEMMINI_ACTIVATION_QUANT_UPPER STREQUAL "BLOCK")
    set(_GGML_GEMMINI_ACTIVATION_QUANT_VALUE 3)
else()
    set(_GGML_GEMMINI_ACTIVATION_QUANT_VALUE 4)
endif()

set(GGML_GEMMINI_BLOCK_SIZE "32" CACHE STRING "Gemmini block size")
set_property(CACHE GGML_GEMMINI_BLOCK_SIZE PROPERTY STRINGS 32 64 128)
if(NOT GGML_GEMMINI_BLOCK_SIZE MATCHES "^(32|64|128)$")
    message(FATAL_ERROR "GGML_GEMMINI_BLOCK_SIZE must be one of: 32, 64, 128; got '${GGML_GEMMINI_BLOCK_SIZE}'")
endif()
set(_GGML_GEMMINI_BLOCK_SIZE_VALUE "${GGML_GEMMINI_BLOCK_SIZE}")

set(GGML_GEMMINI_ACTIVATION_BITS "8" CACHE STRING "Gemmini activation quantization bit width")
set_property(CACHE GGML_GEMMINI_ACTIVATION_BITS PROPERTY STRINGS 4 8 16)
if(NOT GGML_GEMMINI_ACTIVATION_BITS MATCHES "^(4|8|16)$")
    message(FATAL_ERROR "GGML_GEMMINI_ACTIVATION_BITS must be one of: 4, 8, 16; got '${GGML_GEMMINI_ACTIVATION_BITS}'")
endif()
set(_GGML_GEMMINI_ACTIVATION_BITS_VALUE "${GGML_GEMMINI_ACTIVATION_BITS}")

set(GGML_GEMMINI_WEIGHT_BITS "8" CACHE STRING "Gemmini native weight bit width")
set_property(CACHE GGML_GEMMINI_WEIGHT_BITS PROPERTY STRINGS 4 8 16)
if(NOT GGML_GEMMINI_WEIGHT_BITS MATCHES "^(4|8|16)$")
    message(FATAL_ERROR "GGML_GEMMINI_WEIGHT_BITS must be one of: 4, 8, 16; got '${GGML_GEMMINI_WEIGHT_BITS}'")
endif()
set(_GGML_GEMMINI_WEIGHT_BITS_VALUE "${GGML_GEMMINI_WEIGHT_BITS}")

set(GGML_GEMMINI_EXECUTION_BACKEND "HARDWARE" CACHE STRING
    "Gemmini execution backend: HARDWARE or IM2P_SIM")
set_property(CACHE GGML_GEMMINI_EXECUTION_BACKEND PROPERTY STRINGS HARDWARE IM2P_SIM)
if(GGML_GEMMINI_EXECUTION_BACKEND STREQUAL "FPGA_UART")
    message(FATAL_ERROR "FPGA_UART is deprecated and unsupported; use HARDWARE or IM2P_SIM")
endif()
if(NOT GGML_GEMMINI_EXECUTION_BACKEND STREQUAL "HARDWARE" AND
   NOT GGML_GEMMINI_EXECUTION_BACKEND STREQUAL "IM2P_SIM")
    message(FATAL_ERROR
        "GGML_GEMMINI_EXECUTION_BACKEND must be exactly HARDWARE or IM2P_SIM, got '${GGML_GEMMINI_EXECUTION_BACKEND}'")
endif()
if(_GGML_GEMMINI_OPTION_UPPER STREQUAL "OS" OR
   (_GGML_GEMMINI_OPTION_UPPER STREQUAL "CPU" AND
    GGML_GEMMINI_EXECUTION_BACKEND STREQUAL "IM2P_SIM"))
    message(FATAL_ERROR
        "Illegal Gemmini option/backend combination: ${_GGML_GEMMINI_OPTION_UPPER}+${GGML_GEMMINI_EXECUTION_BACKEND}; legal combinations are CPU+HARDWARE, WS+HARDWARE, WS+IM2P_SIM")
endif()
if(NOT GGML_GEMMINI_ACTIVATION_BITS STREQUAL
       "${GGML_GEMMINI_WEIGHT_BITS}")
    message(FATAL_ERROR
        "Gemmini requires matched activation and weight widths")
endif()
set(IM2P_SIM_ROOT "" CACHE PATH "Path to the IM2P.sim source and isolated build artifacts")
set(IM2P_SIM_BUILD_DIR "" CACHE PATH
    "Optional isolated IM2P managed-cache build root (default: IM2P_SIM_ROOT/build)")
set(IM2P_SIM_IMPLEMENTATION "" CACHE STRING
    "IM2P simulator implementation: LEGACY_BSV or GEMMINI_HP1")
set_property(CACHE IM2P_SIM_IMPLEMENTATION PROPERTY STRINGS LEGACY_BSV GEMMINI_HP1)
if(GGML_GEMMINI_EXECUTION_BACKEND STREQUAL "IM2P_SIM" AND
   IM2P_SIM_IMPLEMENTATION STREQUAL "")
    if(CYCLE_SIM)
        set(IM2P_SIM_IMPLEMENTATION "GEMMINI_HP1")
    else()
        set(IM2P_SIM_IMPLEMENTATION "LEGACY_BSV")
    endif()
endif()
if(NOT GGML_GEMMINI_EXECUTION_BACKEND STREQUAL "IM2P_SIM" AND
   NOT IM2P_SIM_IMPLEMENTATION STREQUAL "")
    message(FATAL_ERROR
        "IM2P_SIM_IMPLEMENTATION is valid only with GGML_GEMMINI_EXECUTION_BACKEND=IM2P_SIM")
endif()
if(GGML_GEMMINI_EXECUTION_BACKEND STREQUAL "IM2P_SIM" AND
   NOT IM2P_SIM_IMPLEMENTATION STREQUAL "LEGACY_BSV" AND
   NOT IM2P_SIM_IMPLEMENTATION STREQUAL "GEMMINI_HP1")
    message(FATAL_ERROR
        "IM2P_SIM_IMPLEMENTATION must be LEGACY_BSV or GEMMINI_HP1, got '${IM2P_SIM_IMPLEMENTATION}'")
endif()
if(DEFINED IM2P_DIM AND DEFINED GGML_GEMMINI_DIM AND
   NOT IM2P_DIM STREQUAL GGML_GEMMINI_DIM)
    message(FATAL_ERROR "IM2P_DIM conflicts with GGML_GEMMINI_DIM")
endif()
if(DEFINED IM2P_DIM AND NOT DEFINED GGML_GEMMINI_DIM)
    set(GGML_GEMMINI_DIM "${IM2P_DIM}" CACHE STRING
        "Gemmini array dimension: 16, 32, or 64")
    message(DEPRECATION "IM2P_DIM is deprecated; use GGML_GEMMINI_DIM")
endif()
set(GGML_GEMMINI_DIM "16" CACHE STRING
    "Gemmini array dimension: 16, 32, or 64")
set_property(CACHE GGML_GEMMINI_DIM PROPERTY STRINGS 16 32 64)
if(NOT GGML_GEMMINI_DIM MATCHES "^(16|32|64)$")
    message(FATAL_ERROR
        "GGML_GEMMINI_DIM must be 16, 32, or 64, got '${GGML_GEMMINI_DIM}'")
endif()

set(GGML_GEMMINI_EXSIA_SIGMA "2" CACHE STRING "EXSIA outlier sigma threshold")
if(NOT "${GGML_GEMMINI_EXSIA_SIGMA}" MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "GGML_GEMMINI_EXSIA_SIGMA must be a positive integer, got '${GGML_GEMMINI_EXSIA_SIGMA}'")
endif()
string(LENGTH "${GGML_GEMMINI_EXSIA_SIGMA}" _GGML_GEMMINI_EXSIA_SIGMA_LENGTH)
if(_GGML_GEMMINI_EXSIA_SIGMA_LENGTH GREATER 10 OR
   (_GGML_GEMMINI_EXSIA_SIGMA_LENGTH EQUAL 10 AND
    "${GGML_GEMMINI_EXSIA_SIGMA}" STRGREATER "2147483647"))
    message(FATAL_ERROR
        "GGML_GEMMINI_EXSIA_SIGMA must be a positive integer no greater than 2147483647, got '${GGML_GEMMINI_EXSIA_SIGMA}'")
endif()

foreach(_GGML_GEMMINI_BOOL_VAR IN ITEMS
        GGML_GEMMINI_PRINT_TILE
        GGML_GEMMINI_FULL_C
        GGML_GEMMINI_LOW_D
        GGML_GEMMINI_TRANSPOSE_B
        GGML_GEMMINI_WS_DEBUG
        GGML_GEMMINI_WS_LOOP_CYCLE
        GGML_GEMMINI_DISABLE_WS_REUSE)
    if (NOT ${_GGML_GEMMINI_BOOL_VAR} MATCHES "^[01]$")
        message(FATAL_ERROR
            "${_GGML_GEMMINI_BOOL_VAR} must be 0 or 1, got '${${_GGML_GEMMINI_BOOL_VAR}}'")
    endif()
endforeach()

set(CYCLE_DETAIL "0" CACHE STRING "Enable EXSIA cycle-detail aggregate logs (0|1)")
set_property(CACHE CYCLE_DETAIL PROPERTY STRINGS 0 1)
if (NOT CYCLE_DETAIL MATCHES "^[01]$")
    message(FATAL_ERROR "CYCLE_DETAIL must be 0 or 1, got '${CYCLE_DETAIL}'")
endif()

set(GGML_GEMMINI_EXSIA_PROFILE_SCOPE "OFF" CACHE STRING "ExSIA profile scope (OFF, TIMELINE, STAGE)")
set_property(CACHE GGML_GEMMINI_EXSIA_PROFILE_SCOPE PROPERTY STRINGS OFF TIMELINE STAGE)
string(TOUPPER "${GGML_GEMMINI_EXSIA_PROFILE_SCOPE}" _GGML_GEMMINI_EXSIA_PROFILE_SCOPE_UPPER)
if(NOT _GGML_GEMMINI_EXSIA_PROFILE_SCOPE_UPPER STREQUAL "OFF" AND
   NOT _GGML_GEMMINI_EXSIA_PROFILE_SCOPE_UPPER STREQUAL "TIMELINE" AND
   NOT _GGML_GEMMINI_EXSIA_PROFILE_SCOPE_UPPER STREQUAL "STAGE")
    message(FATAL_ERROR "GGML_GEMMINI_EXSIA_PROFILE_SCOPE must be OFF, TIMELINE, or STAGE, got '${GGML_GEMMINI_EXSIA_PROFILE_SCOPE}'")
endif()
if(_GGML_GEMMINI_EXSIA_PROFILE_SCOPE_UPPER STREQUAL "OFF")
    set(GGML_GEMMINI_EXSIA_PROFILE_SCOPE_VALUE 0)
elseif(_GGML_GEMMINI_EXSIA_PROFILE_SCOPE_UPPER STREQUAL "TIMELINE")
    set(GGML_GEMMINI_EXSIA_PROFILE_SCOPE_VALUE 1)
else()
    set(GGML_GEMMINI_EXSIA_PROFILE_SCOPE_VALUE 2)
endif()

option(GGML_GEMMINI_ENABLE_OPENMP "Enable OpenMP for Gemmini CPU-side kernels" OFF)
# Balanced Radix-256 Residual Matrix Decomposition. OFF is a residual-compensation
# ablation only; it does not select any other compensation path.
option(GGML_GEMMINI_ENABLE_RMD "Enable Balanced Radix-256 residual compensation (RMD)" ON)
set(GGML_GEMMINI_DEFAULT_RMD_BACKEND "CPU" CACHE STRING
    "Default RMD backend: CPU or WS")
set_property(CACHE GGML_GEMMINI_DEFAULT_RMD_BACKEND PROPERTY STRINGS CPU WS)
if (NOT GGML_GEMMINI_DEFAULT_RMD_BACKEND STREQUAL "CPU" AND
    NOT GGML_GEMMINI_DEFAULT_RMD_BACKEND STREQUAL "WS")
    message(FATAL_ERROR
        "GGML_GEMMINI_DEFAULT_RMD_BACKEND must be exactly CPU or WS, got '${GGML_GEMMINI_DEFAULT_RMD_BACKEND}'")
endif()
if (GGML_GEMMINI_DEFAULT_RMD_BACKEND STREQUAL "CPU")
    set(_GGML_GEMMINI_DEFAULT_RMD_BACKEND_VALUE 0)
else()
    set(_GGML_GEMMINI_DEFAULT_RMD_BACKEND_VALUE 1)
endif()
# Public matmul invocation defaults: FULL / STRIPE_PIPELINE.
option(GGML_GEMMINI_ENABLE_STRIPE_MATMUL "Enable strict stripe matmul modes" ON)
option(GGML_GEMMINI_ENABLE_STRIPE_PIPELINE "Enable strict stripe pipeline mode" ON)
set(GGML_GEMMINI_DEFAULT_MATMUL_MODE "FULL" CACHE STRING
    "Default Gemmini matmul mode: FULL or STRIPE_PIPELINE")
set_property(CACHE GGML_GEMMINI_DEFAULT_MATMUL_MODE PROPERTY STRINGS
    FULL STRIPE_PIPELINE)
set(GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY "2" CACHE STRING
    "Default stripe job capacity")
option(GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE
       "Allow GEMMINI_* environment overrides for matmul options" ON)

function(ggml_gemmini_require_bool _var)
    string(TOUPPER "${${_var}}" _GGML_GEMMINI_BOOL_VALUE)
    if (NOT _GGML_GEMMINI_BOOL_VALUE STREQUAL "ON" AND
        NOT _GGML_GEMMINI_BOOL_VALUE STREQUAL "OFF" AND
        NOT _GGML_GEMMINI_BOOL_VALUE STREQUAL "TRUE" AND
        NOT _GGML_GEMMINI_BOOL_VALUE STREQUAL "FALSE" AND
        NOT _GGML_GEMMINI_BOOL_VALUE STREQUAL "YES" AND
        NOT _GGML_GEMMINI_BOOL_VALUE STREQUAL "NO" AND
        NOT _GGML_GEMMINI_BOOL_VALUE STREQUAL "Y" AND
        NOT _GGML_GEMMINI_BOOL_VALUE STREQUAL "N" AND
        NOT _GGML_GEMMINI_BOOL_VALUE STREQUAL "1" AND
        NOT _GGML_GEMMINI_BOOL_VALUE STREQUAL "0")
        message(FATAL_ERROR "${_var} must be a boolean value, got '${${_var}}'")
    endif()
endfunction()

foreach(_GGML_GEMMINI_MATMUL_BOOL IN ITEMS
        GGML_GEMMINI_ENABLE_RMD
        GGML_GEMMINI_ENABLE_STRIPE_MATMUL
        GGML_GEMMINI_ENABLE_STRIPE_PIPELINE
        GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE)
    ggml_gemmini_require_bool(${_GGML_GEMMINI_MATMUL_BOOL})
endforeach()

if (GGML_GEMMINI_ENABLE_RMD)
    set(_GGML_GEMMINI_ENABLE_RMD_VALUE 1)
else()
    set(_GGML_GEMMINI_ENABLE_RMD_VALUE 0)
endif()

set(_GGML_GEMMINI_MATMUL_MODES FULL STRIPE_PIPELINE)
list(FIND _GGML_GEMMINI_MATMUL_MODES "${GGML_GEMMINI_DEFAULT_MATMUL_MODE}"
     _GGML_GEMMINI_DEFAULT_MATMUL_MODE_VALUE)
if (_GGML_GEMMINI_DEFAULT_MATMUL_MODE_VALUE EQUAL -1)
    message(FATAL_ERROR
        "GGML_GEMMINI_DEFAULT_MATMUL_MODE must be FULL or STRIPE_PIPELINE, got '${GGML_GEMMINI_DEFAULT_MATMUL_MODE}'")
endif()
if (GGML_GEMMINI_ENABLE_STRIPE_PIPELINE AND NOT GGML_GEMMINI_ENABLE_STRIPE_MATMUL)
    message(FATAL_ERROR "GGML_GEMMINI_ENABLE_STRIPE_PIPELINE requires GGML_GEMMINI_ENABLE_STRIPE_MATMUL=ON")
endif()
if (NOT GGML_GEMMINI_DEFAULT_MATMUL_MODE STREQUAL "FULL" AND
    NOT GGML_GEMMINI_ENABLE_STRIPE_MATMUL)
    message(FATAL_ERROR "Stripe matmul defaults require GGML_GEMMINI_ENABLE_STRIPE_MATMUL=ON")
endif()
if (GGML_GEMMINI_DEFAULT_MATMUL_MODE STREQUAL "STRIPE_PIPELINE" AND
    NOT GGML_GEMMINI_ENABLE_STRIPE_PIPELINE)
    message(FATAL_ERROR "STRIPE_PIPELINE default requires GGML_GEMMINI_ENABLE_STRIPE_PIPELINE=ON")
endif()
foreach(_GGML_GEMMINI_MATMUL_COUNT IN ITEMS
        GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY)
    if (NOT ${_GGML_GEMMINI_MATMUL_COUNT} MATCHES "^[1-9][0-9]*$")
        message(FATAL_ERROR "${_GGML_GEMMINI_MATMUL_COUNT} must be a positive integer")
    endif()
    string(LENGTH "${${_GGML_GEMMINI_MATMUL_COUNT}}" _GGML_GEMMINI_MATMUL_COUNT_LENGTH)
    if (_GGML_GEMMINI_MATMUL_COUNT_LENGTH GREATER 10 OR
        (_GGML_GEMMINI_MATMUL_COUNT_LENGTH EQUAL 10 AND
         "${${_GGML_GEMMINI_MATMUL_COUNT}}" STRGREATER "4294967295"))
        message(FATAL_ERROR "${_GGML_GEMMINI_MATMUL_COUNT} exceeds uint32 range")
    endif()
endforeach()

foreach(_GGML_GEMMINI_MATMUL_BOOL IN ITEMS
        GGML_GEMMINI_ENABLE_STRIPE_MATMUL
        GGML_GEMMINI_ENABLE_STRIPE_PIPELINE
        GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE)
    if (${_GGML_GEMMINI_MATMUL_BOOL})
        set(_${_GGML_GEMMINI_MATMUL_BOOL}_VALUE 1)
    else()
        set(_${_GGML_GEMMINI_MATMUL_BOOL}_VALUE 0)
    endif()
endforeach()
# ExSIA default mode configures internal activation staging, not the public matmul mode.
set(GGML_GEMMINI_EXSIA_DEFAULT_MODE "SEQUENTIAL" CACHE STRING "ExSIA default mode")
set_property(CACHE GGML_GEMMINI_EXSIA_DEFAULT_MODE PROPERTY STRINGS SEQUENTIAL LOCAL_PARALLEL LOCAL_FOLDING_PIPELINE)
string(TOUPPER "${GGML_GEMMINI_EXSIA_DEFAULT_MODE}" _GGML_GEMMINI_EXSIA_DEFAULT_MODE_UPPER)
set(_GGML_GEMMINI_EXSIA_DEFAULT_MODES SEQUENTIAL LOCAL_PARALLEL LOCAL_FOLDING_PIPELINE)
list(FIND _GGML_GEMMINI_EXSIA_DEFAULT_MODES "${_GGML_GEMMINI_EXSIA_DEFAULT_MODE_UPPER}" _GGML_GEMMINI_EXSIA_DEFAULT_MODE_VALUE)
if (_GGML_GEMMINI_EXSIA_DEFAULT_MODE_VALUE EQUAL -1)
    message(FATAL_ERROR "GGML_GEMMINI_EXSIA_DEFAULT_MODE must be SEQUENTIAL, LOCAL_PARALLEL, or LOCAL_FOLDING_PIPELINE")
endif()

set(GGML_GEMMINI_EXSIA_LOCAL_WORKERS "4" CACHE STRING "ExSIA Local worker count")
if (NOT GGML_GEMMINI_EXSIA_LOCAL_WORKERS MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "GGML_GEMMINI_EXSIA_LOCAL_WORKERS must be a positive integer")
endif()
if (NOT (GGML_GEMMINI_EXSIA_LOCAL_WORKERS EQUAL 3 OR GGML_GEMMINI_EXSIA_LOCAL_WORKERS EQUAL 4))
    message(FATAL_ERROR "GGML_GEMMINI_EXSIA_LOCAL_WORKERS must be 3 or 4")
endif()
if (_GGML_GEMMINI_EXSIA_DEFAULT_MODE_VALUE GREATER 0 AND NOT GGML_GEMMINI_ENABLE_OPENMP)
    message(FATAL_ERROR "Parallel ExSIA default modes require GGML_GEMMINI_ENABLE_OPENMP=ON")
endif()
math(EXPR _GGML_GEMMINI_EXSIA_EXPECTED_OMP_THREADS
    "${GGML_GEMMINI_EXSIA_LOCAL_WORKERS} + 1")

# set log option
set(LOG_DEBUG "1" CACHE STRING "Enable debug logs (0|1)")
set_property(CACHE LOG_DEBUG PROPERTY STRINGS 0 1)
set(LOG_CYCLE "0" CACHE STRING "Enable cycle logs (0|1)")
set_property(CACHE LOG_CYCLE PROPERTY STRINGS 0 1)
set(LOG_DUMP "0" CACHE STRING "Enable tensor dump logs (0|1)")
set_property(CACHE LOG_DUMP PROPERTY STRINGS 0 1)
set(LOG_DUMP_SCALE "0" CACHE STRING "Enable scale dump logs (0|1)")
set_property(CACHE LOG_DUMP_SCALE PROPERTY STRINGS 0 1)
foreach(_GGML_GEMMINI_LOG_BOOL IN ITEMS LOG_DEBUG LOG_CYCLE LOG_DUMP LOG_DUMP_SCALE)
    if (NOT ${_GGML_GEMMINI_LOG_BOOL} MATCHES "^[01]$")
        message(FATAL_ERROR
            "${_GGML_GEMMINI_LOG_BOOL} must be 0 or 1, got '${${_GGML_GEMMINI_LOG_BOOL}}'")
    endif()
endforeach()

if (CYCLE_DETAIL AND NOT LOG_CYCLE)
    message(FATAL_ERROR "CYCLE_DETAIL=1 requires LOG_CYCLE=1")
endif()
if (NOT _GGML_GEMMINI_EXSIA_PROFILE_SCOPE_UPPER STREQUAL "OFF" AND NOT CYCLE_DETAIL)
    message(FATAL_ERROR "GGML_GEMMINI_EXSIA_PROFILE_SCOPE requires CYCLE_DETAIL=1")
endif()
