configure_file(
    "${_GGML_GEMMINI_SOURCE_DIR}/ggml/src/ggml-gemmini/ggml-gemmini-matmul-config.hpp.in"
    "${GGML_GEMMINI_GENERATED_CONFIG_DIR}/ggml-gemmini-matmul-config.hpp"
    @ONLY)

message(STATUS "GGML Gemmini matmul defaults:"
    "\n  array dimension: ${GGML_GEMMINI_DIM}"
    "\n  stripe capability: ${GGML_GEMMINI_ENABLE_STRIPE_MATMUL}"
    "\n  stripe pipeline: ${GGML_GEMMINI_ENABLE_STRIPE_PIPELINE}"
    "\n  default mode: ${GGML_GEMMINI_DEFAULT_MATMUL_MODE}"
    "\n  residual compensation: RMD=${GGML_GEMMINI_ENABLE_RMD}"
    "\n  default RMD backend: ${GGML_GEMMINI_DEFAULT_RMD_BACKEND}"
    "\n  block size: ${GGML_GEMMINI_BLOCK_SIZE}"
    "\n  default stripe job capacity: ${GGML_GEMMINI_DEFAULT_STRIPE_JOB_CAPACITY}"
    "\n  runtime override: ${GGML_GEMMINI_ALLOW_RUNTIME_MATMUL_OVERRIDE}"
    "\n  ExSIA internal mode: ${_GGML_GEMMINI_EXSIA_DEFAULT_MODE_UPPER}"
    "\n  ExSIA workers/team: ${GGML_GEMMINI_EXSIA_LOCAL_WORKERS}/${_GGML_GEMMINI_EXSIA_EXPECTED_OMP_THREADS}")

set(GGML_GEMMINI_COMPILE_DEFS
    PRINT_TILE=${GGML_GEMMINI_PRINT_TILE}
    OPTION=${_GGML_GEMMINI_OPTION_UPPER}
    FULL_C=${GGML_GEMMINI_FULL_C}
    LOW_D=${GGML_GEMMINI_LOW_D}
    TRANSPOSE_B=${GGML_GEMMINI_TRANSPOSE_B}
    GEMMINI_WS_DEBUG=${GGML_GEMMINI_WS_DEBUG}
    GEMMINI_WS_LOOP_CYCLE=${GGML_GEMMINI_WS_LOOP_CYCLE}
    GEMMINI_DISABLE_WS_REUSE=${GGML_GEMMINI_DISABLE_WS_REUSE}
    GGML_GEMMINI_COMPUTE_TYPE=${_GGML_GEMMINI_COMPUTE_TYPE_VALUE}
    GGML_GEMMINI_DEQUANT_FP_TEST=${_GGML_GEMMINI_DEQUANT_FP_TEST_VALUE}
    GGML_GEMMINI_ACTIVATION_QUANT=${_GGML_GEMMINI_ACTIVATION_QUANT_VALUE}
    GGML_GEMMINI_BLOCK_SIZE=${_GGML_GEMMINI_BLOCK_SIZE_VALUE}
    GGML_GEMMINI_EXSIA_SIGMA=${GGML_GEMMINI_EXSIA_SIGMA}
    GGML_GEMMINI_ACTIVATION_BITS=${_GGML_GEMMINI_ACTIVATION_BITS_VALUE}
    GGML_GEMMINI_WEIGHT_BITS=${_GGML_GEMMINI_WEIGHT_BITS_VALUE}
    GGML_GEMMINI_CONFIGURED_DIM=${GGML_GEMMINI_DIM}
)
if(CYCLE_SIM AND _GGML_GEMMINI_OPTION_UPPER STREQUAL "WS")
    list(APPEND GGML_GEMMINI_COMPILE_DEFS
        GGML_GEMMINI_EXECUTION_BACKEND_IM2P_SIM=1
        IM2P_SIM_IMPLEMENTATION_GEMMINI_HP1=1)
elseif(GGML_GEMMINI_EXECUTION_BACKEND STREQUAL "IM2P_SIM")
    list(APPEND GGML_GEMMINI_COMPILE_DEFS GGML_GEMMINI_EXECUTION_BACKEND_IM2P_SIM=1)
    if(IM2P_SIM_IMPLEMENTATION STREQUAL "GEMMINI_HP1")
        list(APPEND GGML_GEMMINI_COMPILE_DEFS IM2P_SIM_IMPLEMENTATION_GEMMINI_HP1=1)
    endif()
else()
    list(APPEND GGML_GEMMINI_COMPILE_DEFS GGML_GEMMINI_EXECUTION_BACKEND_HARDWARE=1)
endif()

set(GGML_GEMMINI_RUNTIME_COMPILE_DEFS
    GGML_GEMMINI_ACT_METRICS=${GGML_GEMMINI_ACT_QUANT_METRICS}
    GGML_GEMMINI_SCALE_METRICS=${GGML_GEMMINI_SCALE_METRICS}
    GGML_GEMMINI_ACT_QUANT_METRICS=${GGML_GEMMINI_ACT_QUANT_METRICS}
    GGML_GEMMINI_RESIDUAL_METRICS=${GGML_GEMMINI_RESIDUAL_METRICS}
    CYCLE_SIM=${CYCLE_SIM}
    LOG_DEBUG=${LOG_DEBUG}
    LOG_CYCLE=${LOG_CYCLE}
    LOG_DUMP=${LOG_DUMP}
    LOG_DUMP_SCALE=${LOG_DUMP_SCALE}
    GEMMINI_VERIFY_DEQ=1
    CYCLE_DETAIL=${CYCLE_DETAIL}
    GGML_GEMMINI_COMPUTE_TYPE=${_GGML_GEMMINI_COMPUTE_TYPE_VALUE}
    GGML_GEMMINI_DEQUANT_FP_TEST=${_GGML_GEMMINI_DEQUANT_FP_TEST_VALUE}
    GGML_GEMMINI_ACTIVATION_QUANT=${_GGML_GEMMINI_ACTIVATION_QUANT_VALUE}
    GGML_GEMMINI_EXSIA_DEFAULT_MODE_VALUE=${_GGML_GEMMINI_EXSIA_DEFAULT_MODE_VALUE}
    GGML_GEMMINI_EXSIA_LOCAL_WORKERS=${GGML_GEMMINI_EXSIA_LOCAL_WORKERS}
    GGML_GEMMINI_ENABLE_RMD=${_GGML_GEMMINI_ENABLE_RMD_VALUE}
    GGML_GEMMINI_ACTIVATION_BITS=${_GGML_GEMMINI_ACTIVATION_BITS_VALUE}
    GGML_GEMMINI_WEIGHT_BITS=${_GGML_GEMMINI_WEIGHT_BITS_VALUE}
)

list(APPEND GGML_GEMMINI_COMPILE_DEFS ${GGML_GEMMINI_RUNTIME_COMPILE_DEFS})
if (LLAMA_BUILD_TESTS AND GGML_GEMMINI)
    list(APPEND GGML_GEMMINI_COMPILE_DEFS GGML_GEMMINI_TEST_OBSERVER=1)
endif()
set(GGML_GEMMINI_UTILS_COMPILE_DEFS
    GGML_GEMMINI_ACT_METRICS=${GGML_GEMMINI_ACT_QUANT_METRICS}
    GGML_GEMMINI_SCALE_METRICS=${GGML_GEMMINI_SCALE_METRICS}
    GGML_GEMMINI_ACT_QUANT_METRICS=${GGML_GEMMINI_ACT_QUANT_METRICS}
    GGML_GEMMINI_RESIDUAL_METRICS=${GGML_GEMMINI_RESIDUAL_METRICS}
    LOG_DEBUG=${LOG_DEBUG}
    LOG_CYCLE=${LOG_CYCLE}
    CYCLE_DETAIL=${CYCLE_DETAIL})
