set(EVALUATION_HP1 0)
if(CYCLE_SIM OR IM2P_SIM_IMPLEMENTATION STREQUAL "GEMMINI_HP1" OR IM2P_FPGA_ARCH STREQUAL "GEMMINI_HP1")
    set(EVALUATION_HP1 1)
endif()
add_executable(llama-eval-workload eval.cpp evaluation-trace.cpp)
target_compile_features(llama-eval-workload PRIVATE cxx_std_17)
target_compile_definitions(llama-eval-workload PRIVATE
    ${GGML_GEMMINI_RUNTIME_COMPILE_DEFS}
    GGML_GEMMINI_DIM=${GGML_GEMMINI_DIM}
    EVALUATION_BACKEND="${GGML_GEMMINI_EXECUTION_BACKEND}"
    EVALUATION_GEMMINI_OPTION="${GGML_GEMMINI_OPTION}"
    EVALUATION_ACTIVATION_MODE="${GGML_GEMMINI_ACTIVATION_QUANT}"
    EVALUATION_BLOCK_SIZE=${GGML_GEMMINI_BLOCK_SIZE}
    EVALUATION_RMD_BACKEND="${GGML_GEMMINI_DEFAULT_RMD_BACKEND}"
    EVALUATION_MATMUL_MODE="${GGML_GEMMINI_DEFAULT_MATMUL_MODE}"
    EVALUATION_HP1=${EVALUATION_HP1}
    EVALUATION_CUDA=$<BOOL:${GGML_CUDA}>
    EVALUATION_CPU_CYCLE_LOG=$<BOOL:${GGML_CPU_CYCLE_LOG}>
    EVALUATION_GEMMINI=$<BOOL:${GGML_GEMMINI}>)
target_link_libraries(llama-eval-workload PRIVATE common llama ggml-gemmini-utils)
install(TARGETS llama-eval-workload RUNTIME)
